// packages/wrappers/react/src/components/AparteChat.tsx
'use client';

import React, {
    useEffect,
    useId,
    useRef,
    useState,
    forwardRef,
    useImperativeHandle,
} from 'react';
import { AparteChatHost, isAwaitingReply, type AparteChatHostBinding, type AparteConfigClass, type AparteChatImperativeApi } from '@aparte/core';
import type { AparteMessage, AparteSendEventDetail, AparteActionEventDetail } from '../types.js';

export interface AparteChatProps {
    /**
     * Messages on the active path. **Optional** — omit for an uncontrolled chat
     * that starts empty (defaults to `[]`); pass it together with
     * `onMessagesChange` to control the list from the parent.
     */
    messages?: AparteMessage[];
    placeholder?: string;
    disabled?: boolean;
    isTyping?: boolean;
    typingText?: string;
    /** When false, Shift+Enter submits and a bare Enter inserts a newline. */
    submitOnEnter?: boolean;
    /** Freeze viewport spacer recalculation for this many ms after a conv swap. */
    layoutTransitionMs?: number;
    /**
     * Opt in to the "centered composer when empty" layout: while the message
     * list is empty the composer sits vertically centered with the `emptyState`
     * content above it, then slides to the bottom on the first message (~0.3s).
     * Off by default — purely additive: adds the `aparte-chat-container--auto-center`
     * modifier + a `data-aparte-empty` attribute that the shipped `aparte.css` recipe
     * keys off. No effect unless you also render an `emptyState`.
     */
    centerWhenEmpty?: boolean;
    /**
     * Add the file picker + chips strip to the default composer shell. **Off by
     * default**, because the capability needs a host that consumes the files: an
     * `AparteClient` inlines them per its `rawFileInject` option, but if you drive
     * your own loop you must read `event.files` in `onMessageSent` — otherwise the
     * file the user deliberately attached is dropped in silence. No effect when you
     * pass your own `composer` (drop `<aparte-composer-add-attachment>` and
     * `<aparte-composer-attachments>` in it yourself).
     */
    attachments?: boolean;
    /**
     * Active conversation id. When set, the wrapper loads/persists via the
     * `ConversationManager` registered in `AparteConfig` (set `null` to deselect).
     */
    conversationId?: string | null;
    /**
     * Custom composer content, rendered inside `<aparte-composer>` in place of the
     * default shell (input · send, plus the attachment primitives when
     * `attachments` is set). Compose the headless
     * `aparte-composer-*` primitives freely — e.g. a skin-specific layout. Omit for
     * the default shell. The `<aparte-composer>` element (and its placeholder /
     * disabled / submit-on-enter behaviour) is always provided by the wrapper.
     */
    composer?: React.ReactNode;
    /**
     * Render your OWN element per message in place of `<aparte-chat-bubble>`.
     * Opt-in — omit for the default bubble. The returned node is driven by the
     * reactive message list, so it updates live during streaming (no need to
     * implement any imperative interface): re-render from `message.content` /
     * `message.segments`. Note the built-in action bar (retry/edit/branch) and
     * the imperative streaming push are the native bubble's — a custom bubble
     * owns whatever it wires (it can dispatch `aparte-retry` etc. or call the
     * wrapper's imperative API).
     */
    renderBubble?: (message: AparteMessage) => React.ReactNode;
    /**
     * Welcome / placeholder content shown INSIDE the viewport while there are no
     * messages (a real "empty state" region, not a workaround via `aboveComposer`).
     * Replaced by the message list on the first message.
     */
    emptyState?: React.ReactNode;
    /**
     * Content rendered ABOVE the composer (e.g. a disclaimer banner, a
     * "scroll to bottom" affordance, a context chip). Ignored when a full
     * custom `composer` replaces the shell.
     */
    aboveComposer?: React.ReactNode;
    /**
     * The composer's bottom row — a mode picker, a model selector, a token counter.
     * Rendered inside core's `<aparte-composer-toolbar>`; nothing is rendered at all
     * when you pass nothing, so an unused row never draws its separator.
     *
     * **Placement is the DOM order.** There is no left/center/right slot: put things in
     * the order you want them, and push a control (with everything after it) to the end
     * with `margin-inline-start: auto`. That is a logical property, so the row reads
     * correctly in a right-to-left locale with no extra work.
     *
     * Ignored when a full custom `composer` replaces the shell.
     *
     * @example
     * <AparteChat
     *   messages={messages}
     *   onMessagesChange={setMessages}
     *   toolbar={<>
     *     <ModePicker value={mode} onChange={setMode} />
     *     <ModelSelector style={{ marginInlineStart: 'auto' }} />
     *   </>}
     * />
     */
    toolbar?: React.ReactNode;

    /**
     * Notification that the user submitted a message from the composer. The
     * user's message is **appended to the thread automatically** (optimistic UI)
     * before this fires — do NOT add it again here. In an uncontrolled chat,
     * appending it duplicates it; in a controlled chat, mirror it into your own
     * `messages`. Use this for side-effects: scroll, analytics, backend send.
     */
    onMessageSent?: (event: AparteSendEventDetail) => void;
    /**
     * Fired when a custom bubble action (registered via
     * `AparteConfig.registerAction` with `zones: ['bubble']`) is clicked — a typed
     * wrapper over the bubbling `aparte-action` DOM event. Dispatch on `detail.actionId`.
     */
    onAction?: (detail: AparteActionEventDetail) => void;
    /**
     * Fired when the active message path changes (branch navigation / edit /
     * retry / streaming). Set the result back as the `messages` prop.
     */
    onMessagesChange?: (messages: AparteMessage[]) => void;
    /** Fired when a message is appended internally (e.g. by AparteClient). */
    onMessageAppended?: (message: AparteMessage) => void;
    /** Fired when the typing/"thinking" indicator should toggle. */
    onTypingChange?: (isTyping: boolean) => void;
    /** Fired when the controller lazily creates a conversation on first send. */
    onConversationCreated?: (id: string) => void;

    /**
     * Instance {@link AparteConfigClass} for this chat. When set, every aparté
     * component rendered inside resolves THIS config instead of the global
     * `AparteConfig` singleton — letting several independently-configured chats
     * (different providers, tools, renderers) coexist on one page. Omit for the
     * global config. Read once when the host mounts.
     */
    config?: AparteConfigClass;
}

/**
 * The React ref handle for `<AparteChat>` — the canonical imperative surface
 * shared by all four wrappers (see `AparteChatImperativeApi` in `@aparte/core`).
 */
export type AparteChatHandle = AparteChatImperativeApi;

export const AparteChat = forwardRef<AparteChatHandle, AparteChatProps>(function AparteChat(
    {
        messages = [],
        placeholder = 'Type a message...',
        disabled = false,
        isTyping = false,
        typingText = 'Assistant is thinking...',
        submitOnEnter = true,
        layoutTransitionMs = 0,
        centerWhenEmpty = false,
        attachments = false,
        conversationId = null,
        composer,
        renderBubble,
        emptyState,
        aboveComposer,
        toolbar,
        config,
        onMessageSent,
        onAction,
        onMessagesChange,
        onMessageAppended,
        onTypingChange,
        onConversationCreated,
    },
    ref,
) {
    // useId() is SSR-stable (server and client agree), so no hydration mismatch.
    // Strip ':' so the id is also safe in CSS/querySelector, not just getElementById.
    const hostId = `aparte-chat-${useId().replace(/:/g, '')}`;
    const hostElRef = useRef<HTMLDivElement>(null);
    const viewportRef = useRef<HTMLElement>(null);
    const composerRef = useRef<HTMLElement>(null);

    // Authoritative message list lives in a ref (the host reads it synchronously);
    // `renderMessages` state drives the declarative bubble list.
    const messagesRef = useRef<AparteMessage[]>(messages);
    const [renderMessages, setRenderMessages] = useState<AparteMessage[]>(messages);
    const [typingActive, setTypingActive] = useState(isTyping);
    const [, setIsStreaming] = useState(false);

    const hostRef = useRef<AparteChatHost | null>(null);
    const lastConvRef = useRef<string | null>(conversationId);

    // Keep the latest prop callbacks in a ref so the host's stable binding always
    // calls the current handlers without recreating the host.
    const cbRef = useRef({ onMessageSent, onAction, onMessagesChange, onMessageAppended, onTypingChange, onConversationCreated });
    cbRef.current = { onMessageSent, onAction, onMessagesChange, onMessageAppended, onTypingChange, onConversationCreated };

    const applyMessages = (m: AparteMessage[]) => {
        messagesRef.current = m;
        setRenderMessages(m);
    };

    // Create the host once after mount.
    useEffect(() => {
        const host = hostElRef.current;
        if (!host) return;
        const binding: AparteChatHostBinding = {
            hostId,
            host,
            viewport: viewportRef.current,
            getMessages: () => messagesRef.current,
            setMessages: (m) => applyMessages(m as AparteMessage[]),
            onMessagesChange: (m) => cbRef.current.onMessagesChange?.(m as AparteMessage[]),
            onMessageAppended: (m) => cbRef.current.onMessageAppended?.(m as AparteMessage),
            onTypingChange: (t) => { setTypingActive(t); cbRef.current.onTypingChange?.(t); },
            onStreamingChange: (id) => setIsStreaming(id !== null),
            afterRender: (cb) => { requestAnimationFrame(() => cb()); },
            resetComposer: () => (composerRef.current as unknown as { reset?: () => void })?.reset?.(),
        };
        const h = new AparteChatHost(binding, {
            layoutTransitionMs,
            conversationId: conversationId ?? null,
            onConversationCreated: (id) => cbRef.current.onConversationCreated?.(id),
            config,
        });
        hostRef.current = h;
        const teardown = h.bind();
        return () => { teardown(); hostRef.current = null; };
        // The host is created once per mount (keyed by the stable hostId); prop
        // changes flow through cbRef / dedicated effects, not by recreating it.
    }, [hostId]);

    // Parent push: sync the prop into the authoritative list. Guarded by ref
    // identity so the host's own emit→parent→prop round-trip doesn't loop.
    useEffect(() => {
        if (messages === messagesRef.current) return;
        applyMessages(messages);
        if (messages.length === 0) hostRef.current?.clearRenderCache();
    }, [messages]);

    // Reconcile bubbles whenever the rendered list changes (the host queries the
    // DOM for `<aparte-chat-bubble message-id>` elements and pushes segments).
    useEffect(() => { hostRef.current?.syncBubbles(); }, [renderMessages]);

    // Controlled typing indicator: reflect the prop, while the host may flip it
    // off internally on the first streamed token.
    useEffect(() => { setTypingActive(isTyping); }, [isTyping]);

    // Conversation id changes (the initial value is loaded by the host on bind).
    useEffect(() => {
        if (conversationId === lastConvRef.current) return;
        lastConvRef.current = conversationId;
        void hostRef.current?.setConversationId(conversationId ?? null);
    }, [conversationId]);

    // Surface composer sends to the consumer (the controller handles the
    // conversation side separately via its own host listener).
    useEffect(() => {
        const composer = composerRef.current;
        if (!composer) return;
        const onSend = (e: Event) => {
            (viewportRef.current as unknown as { requestSmoothScroll?: () => void })?.requestSmoothScroll?.();
            cbRef.current.onMessageSent?.((e as CustomEvent<AparteSendEventDetail>).detail);
        };
        composer.addEventListener('aparte-send', onSend);
        return () => composer.removeEventListener('aparte-send', onSend);
    }, []);

    // aparte-composer exposes `placeholder`/`disabled` as GETTER-ONLY accessors.
    // React 19 sets matching props as PROPERTIES on custom elements, which throws
    // ("Cannot set property placeholder ... which has only a getter"). Set them as
    // attributes imperatively instead (the getter reads the attribute).
    useEffect(() => {
        const composer = composerRef.current;
        if (!composer) return;
        composer.setAttribute('placeholder', placeholder);
        if (disabled) composer.setAttribute('disabled', '');
        else composer.removeAttribute('disabled');
    }, [placeholder, disabled]);

    // Custom bubble actions bubble to the host root as `aparte-action`; surface them
    // as a typed prop.
    useEffect(() => {
        const host = hostElRef.current;
        if (!host) return;
        const onAct = (e: Event) => cbRef.current.onAction?.((e as CustomEvent<AparteActionEventDetail>).detail);
        host.addEventListener('aparte-action', onAct);
        return () => host.removeEventListener('aparte-action', onAct);
    }, []);

    useImperativeHandle(ref, (): AparteChatHandle => ({
        appendMessage: (m) => hostRef.current?.appendMessage(m),
        updateMessage: (id, u) => hostRef.current?.updateMessage(id, u),
        updateLastMessage: (c, o) => hostRef.current?.updateLastMessage(c, o),
        addSegment: (s) => hostRef.current?.addSegment(s),
        updateSegment: (id, u) => hostRef.current?.updateSegment(id, u),
        removeSegment: (id) => hostRef.current?.removeSegment(id),
        appendToSegment: (id, c) => hostRef.current?.appendToSegment(id, c),
        getMessages: () => hostRef.current?.getMessages() ?? messagesRef.current,
        clearMessages: () => hostRef.current?.clearMessages(),
        addBranch: (id) => hostRef.current?.addBranch(id) ?? 0,
        addSiblingOf: (id, m) => hostRef.current?.addSiblingOf(id, m) ?? null,
        truncateFrom: (id) => hostRef.current?.truncateFrom(id),
        truncateResponsesAfter: (id) => hostRef.current?.truncateResponsesAfter(id),
        injectTokenStream: (id, tokens) => hostRef.current?.streamTokens(id, tokens) ?? Promise.resolve(),
        stopTokenStream: () => hostRef.current?.stopTokenStream(),
        setConversationId: (id) => hostRef.current?.setConversationId(id) ?? Promise.resolve(),
        scrollToBottom: () => (viewportRef.current as unknown as { scrollToBottom?: () => void })?.scrollToBottom?.(),
        focusInput: () => (composerRef.current as unknown as { focus?: () => void })?.focus?.(),
        isStreaming: () => hostRef.current?.isStreaming ?? false,
        getViewport: () => viewportRef.current,
    }), []);

    return (
        <div
            className={`aparte-chat-container${centerWhenEmpty ? ' aparte-chat-container--auto-center' : ''}`}
            data-aparte-chat=""
            data-aparte-empty={centerWhenEmpty && renderMessages.length === 0 ? '' : undefined}
            id={hostId}
            ref={hostElRef}
        >
            <aparte-chat-viewport ref={viewportRef as React.Ref<HTMLElement>} framework-managed="">
                {renderMessages.length === 0 && emptyState}
                {renderMessages.map((m) => (
                    renderBubble
                        ? <React.Fragment key={m.id}>{renderBubble(m)}</React.Fragment>
                        : (
                            <aparte-chat-bubble
                                key={m.id}
                                message-id={m.id}
                                data-role={m.role}
                                timestamp={m.timestamp}
                                content={m.content}
                                streaming={isAwaitingReply(m) ? '' : undefined}
                            />
                        )
                ))}
                <aparte-chat-status visible={typingActive ? '' : undefined} text={typingText} />
            </aparte-chat-viewport>

            {aboveComposer}

            <aparte-composer
                ref={composerRef as React.Ref<HTMLElement>}
                target={hostId}
                submit-on-enter={submitOnEnter ? undefined : 'false'}
            >
                {composer ?? (
                    <div className="aparte-composer-shell">
                        {attachments && <aparte-composer-attachments />}
                        <div className="aparte-composer-row">
                            {attachments && <aparte-composer-add-attachment />}
                            <aparte-composer-input />
                            <aparte-composer-send />
                        </div>
                        {toolbar != null && (
                            <aparte-composer-toolbar>{toolbar}</aparte-composer-toolbar>
                        )}
                    </div>
                )}
            </aparte-composer>
        </div>
    );
});

AparteChat.displayName = 'AparteChat';

// packages/wrappers/vue/src/components/AparteChat.vue
<script setup lang="ts">
import { ref, watch, onMounted, onBeforeUnmount, nextTick, useId, toRaw } from 'vue';
import { AparteChatHost, isAwaitingReply, type AparteChatHostBinding, type AparteConfigClass, type AparteChatImperativeApi } from '@aparte/core';
import type { AparteMessage, AparteSegment, AparteSendEventDetail, AparteActionEventDetail } from '../types.js';

interface Props {
  /** Optional: omit for an uncontrolled chat (defaults to []); use `v-model:messages` to control. */
  messages?: AparteMessage[];
  placeholder?: string;
  disabled?: boolean;
  isTyping?: boolean;
  typingText?: string;
  /** When false, Shift+Enter submits and a bare Enter inserts a newline. */
  submitOnEnter?: boolean;
  /** Freeze viewport spacer recalculation for this many ms after a conv swap. */
  layoutTransitionMs?: number;
  /**
   * Opt in to the "centered composer when empty" layout: the composer sits
   * vertically centered with the `empty-state` slot above it while the list is
   * empty, then slides to the bottom on the first message (~0.3s). Off by
   * default — additive (adds the `--auto-center` modifier + a `data-aparte-empty`
   * attribute the shipped `aparte.css` recipe keys off).
   */
  centerWhenEmpty?: boolean;
  /**
   * Add the file picker + chips strip to the default composer shell. **Off by
   * default**, because the capability needs a host that consumes the files: an
   * `AparteClient` inlines them per its `rawFileInject` option, but if you drive
   * your own loop you must read `event.files` on `messageSent` — otherwise the file
   * the user deliberately attached is dropped in silence. No effect when you fill
   * the `composer` slot (drop `<aparte-composer-add-attachment>` and
   * `<aparte-composer-attachments>` in it yourself).
   */
  attachments?: boolean;
  /** Active conversation id (loads/persists via the registered ConversationManager). */
  conversationId?: string | null;
  /**
   * Instance {@link AparteConfigClass} for this chat. When set, aparté components
   * inside resolve THIS config instead of the global `AparteConfig` singleton, so
   * several independently-configured chats can coexist on one page. Omit for the
   * global config. Read once when the host mounts.
   */
  config?: AparteConfigClass;
}

const props = withDefaults(defineProps<Props>(), {
  messages: () => [],
  placeholder: 'Type a message...',
  disabled: false,
  isTyping: false,
  typingText: 'Assistant is thinking...',
  submitOnEnter: true,
  layoutTransitionMs: 0,
  centerWhenEmpty: false,
  attachments: false,
  conversationId: null,
});

const emit = defineEmits<{
  /**
   * User submitted a message from the composer. The message is **appended to
   * the thread automatically** (optimistic UI) before this fires — do NOT add
   * it again in the handler (uncontrolled → duplicates; controlled → mirror it
   * into your own `messages`). For side-effects: scroll, analytics, send.
   */
  messageSent: [event: AparteSendEventDetail];
  /** A custom bubble action (registerBubbleAction) was clicked — typed aparte-action. */
  action: [detail: AparteActionEventDetail];
  /** Active path changed (branch nav/edit/retry/streaming) — bind back to `messages`. */
  messagesChange: [messages: AparteMessage[]];
  /** Same payload as `messagesChange`, enabling `v-model:messages`. */
  'update:messages': [messages: AparteMessage[]];
  messageAppended: [message: AparteMessage];
  /** The typing/"thinking" indicator toggled (the host flips it off on the first streamed token). */
  typingChange: [isTyping: boolean];
  conversationCreated: [id: string];
}>();

// useId() (Vue 3.5+) is SSR-stable — server and client agree, no hydration mismatch.
const hostId = `aparte-chat-${useId()}`;
const rootRef = ref<HTMLElement>();
const viewportRef = ref<HTMLElement>();
const composerRef = ref<HTMLElement>();
const internalMessages = ref<AparteMessage[]>([...props.messages]);
const typingActive = ref(props.isTyping);

let host: AparteChatHost | null = null;
let teardown: (() => void) | null = null;

function onSend(e: Event) {
  (viewportRef.value as unknown as { requestSmoothScroll?: () => void })?.requestSmoothScroll?.();
  emit('messageSent', (e as CustomEvent<AparteSendEventDetail>).detail);
}

// Custom bubble actions bubble to the root as `aparte-action` — surface them typed.
function onAction(e: Event) {
  emit('action', (e as CustomEvent<AparteActionEventDetail>).detail);
}

onMounted(() => {
  const binding: AparteChatHostBinding = {
    hostId,
    host: rootRef.value as HTMLElement,
    viewport: viewportRef.value ?? null,
    getMessages: () => internalMessages.value,
    setMessages: (m) => { internalMessages.value = m as AparteMessage[]; },
    onMessagesChange: (m) => { emit('messagesChange', m as AparteMessage[]); emit('update:messages', m as AparteMessage[]); },
    onMessageAppended: (m) => emit('messageAppended', m as AparteMessage),
    onTypingChange: (t) => { typingActive.value = t; emit('typingChange', t); },
    onStreamingChange: () => { /* exposed via isStreaming() */ },
    afterRender: (cb) => { void nextTick(cb); },
    resetComposer: () => (composerRef.value as unknown as { reset?: () => void })?.reset?.(),
  };
  host = new AparteChatHost(binding, {
    layoutTransitionMs: props.layoutTransitionMs,
    conversationId: props.conversationId ?? null,
    onConversationCreated: (id) => emit('conversationCreated', id),
    // Unwrap Vue's reactive proxy: the config is a plain class with internal
    // Map registries the host/components must operate on directly, not through a
    // deep reactive proxy (which would wrap those Maps and break lookups).
    config: props.config ? toRaw(props.config) : undefined,
  });
  teardown = host.bind();
  host.syncBubbles();
  composerRef.value?.addEventListener('aparte-send', onSend);
  rootRef.value?.addEventListener('aparte-action', onAction);
});

onBeforeUnmount(() => {
  composerRef.value?.removeEventListener('aparte-send', onSend);
  rootRef.value?.removeEventListener('aparte-action', onAction);
  teardown?.();
  teardown = null;
  host = null;
});

// Parent push → internal list (guarded against the host's own emit round-trip).
watch(() => props.messages, (m) => {
  if (m === internalMessages.value) return;
  internalMessages.value = [...m];
  if (m.length === 0) host?.clearRenderCache();
});

// Reconcile bubbles after the rendered list changes (host queries the DOM).
watch(internalMessages, () => { void nextTick(() => host?.syncBubbles()); });

watch(() => props.isTyping, (t) => { typingActive.value = t; });
watch(() => props.conversationId, (id) => { void host?.setConversationId(id ?? null); });

// ── Imperative API (forwards to the host) ──
const appendMessage = (m: AparteMessage) => host?.appendMessage(m);
const updateMessage = (id: string, u: Partial<AparteMessage>) => host?.updateMessage(id, u);
const updateLastMessage = (c: string, o?: { append?: boolean }) => host?.updateLastMessage(c, o);
const addSegment = (s: AparteSegment) => host?.addSegment(s);
const updateSegment = (id: string, u: Partial<AparteSegment>) => host?.updateSegment(id, u);
const removeSegment = (id: string) => host?.removeSegment(id);
const appendToSegment = (id: string, c: string) => host?.appendToSegment(id, c);
const getMessages = () => host?.getMessages() ?? internalMessages.value;
const clearMessages = () => host?.clearMessages();
const addBranch = (id: string) => host?.addBranch(id) ?? 0;
const addSiblingOf = (id: string, m: AparteMessage) => host?.addSiblingOf(id, m) ?? null;
const truncateFrom = (id: string) => host?.truncateFrom(id);
const truncateResponsesAfter = (id: string) => host?.truncateResponsesAfter(id);
const injectTokenStream = (id: string, tokens: AsyncIterable<string>) =>
  host?.streamTokens(id, tokens) ?? Promise.resolve();
const stopTokenStream = () => host?.stopTokenStream();
const setConversationId = (id: string | null) => host?.setConversationId(id) ?? Promise.resolve();
const scrollToBottom = () => (viewportRef.value as unknown as { scrollToBottom?: () => void })?.scrollToBottom?.();
const focusInput = () => (composerRef.value as unknown as { focus?: () => void })?.focus?.();
const isStreaming = () => host?.isStreaming ?? false;

// `getViewport()` (not a raw `viewport` ref): the same accessor on all four
// wrappers — Svelte 4 can only expose functions, so the shared name is one.
const getViewport = () => viewportRef.value ?? null;

// `satisfies` makes a dropped or mistyped method a compile error — the canonical
// AparteChatImperativeApi is enforced here, not just aliased for consumers.
defineExpose({
  appendMessage, updateMessage, updateLastMessage, addSegment, updateSegment, removeSegment,
  appendToSegment, getMessages, clearMessages, addBranch, addSiblingOf, truncateFrom,
  truncateResponsesAfter, injectTokenStream, stopTokenStream, setConversationId,
  scrollToBottom, focusInput, isStreaming, getViewport,
} satisfies AparteChatImperativeApi);
</script>

<template>
  <div
    :class="['aparte-chat-container', { 'aparte-chat-container--auto-center': centerWhenEmpty }]"
    data-aparte-chat
    :data-aparte-empty="centerWhenEmpty && internalMessages.length === 0 ? '' : null"
    :id="hostId"
    ref="rootRef"
  >
    <aparte-chat-viewport ref="viewportRef" framework-managed="">
      <!-- Welcome / placeholder shown inside the viewport while there are no
           messages (a real empty-state region). -->
      <slot v-if="internalMessages.length === 0" name="empty-state" />
      <!-- `bubble` scoped slot renders your OWN element per message in place of
           <aparte-chat-bubble>; driven by the reactive list so it streams live. -->
      <template v-for="m in internalMessages" :key="m.id">
        <slot name="bubble" :message="m">
          <aparte-chat-bubble
            :message-id="m.id"
            :data-role="m.role"
            :timestamp="m.timestamp"
            :content="m.content"
            :streaming="isAwaitingReply(m) ? '' : null"
          />
        </slot>
      </template>
      <aparte-chat-status :visible="typingActive ? '' : null" :text="typingText" />
    </aparte-chat-viewport>

    <!-- Content above the composer (banner, disclaimer, context chip). -->
    <slot name="above-composer" />

    <!-- `.attr` forces attribute-setting: core's <aparte-composer> exposes
         `placeholder`/`disabled` as getter-only accessors, so Vue's default
         property-set (it prefers props on custom elements) would throw and the
         value would silently never apply. -->
    <aparte-composer
      ref="composerRef"
      :target="hostId"
      :placeholder.attr="placeholder"
      :disabled.attr="disabled ? '' : null"
      :submit-on-enter="submitOnEnter ? null : 'false'"
    >
      <!-- Custom composer via the `composer` slot; falls back to the default
           shell (input · send, plus the attachment primitives when `attachments`
           is set). Compose the headless aparte-composer-* primitives freely for a
           skin-specific layout. -->
      <slot name="composer">
        <div class="aparte-composer-shell">
          <aparte-composer-attachments v-if="attachments"></aparte-composer-attachments>
          <div class="aparte-composer-row">
            <aparte-composer-add-attachment v-if="attachments"></aparte-composer-add-attachment>
            <aparte-composer-input></aparte-composer-input>
            <aparte-composer-send></aparte-composer-send>
          </div>
          <!-- The composer's bottom row. ONE slot: placement is the DOM order, and
               `margin-inline-start: auto` pushes a control to the end (a logical
               property, so it reads correctly in RTL). Nothing is rendered at all when
               the slot is unused. -->
          <aparte-composer-toolbar v-if="$slots.toolbar">
            <slot name="toolbar" />
          </aparte-composer-toolbar>
        </div>
      </slot>
    </aparte-composer>
  </div>
</template>
