// packages/wrappers/svelte/src/lib/AparteChat.svelte
<script lang="ts">
  import { onMount, onDestroy, tick, createEventDispatcher } from 'svelte';
  import { AparteChatHost, isAwaitingReply, type AparteChatHostBinding, type AparteConfigClass, type AparteChatImperativeApi } from '@aparte/core';
  import type { AparteMessage, AparteSegment, AparteSendEventDetail, AparteActionEventDetail } from './types';

  export let messages: AparteMessage[] = [];
  export let placeholder = 'Type a message...';
  export let disabled = false;
  export let isTyping = false;
  export let typingText = 'Assistant is thinking...';
  /** When false, Shift+Enter submits and a bare Enter inserts a newline. */
  export let submitOnEnter = true;
  /** Freeze viewport spacer recalculation for this many ms after a conv swap. */
  export let layoutTransitionMs = 0;
  /**
   * Opt in to the "centered composer when empty" layout: the composer sits
   * vertically centered with the `empty-state` slot above it while the list is
   * empty, then slides to the bottom on the first message (~0.3s). Off by
   * default — additive.
   */
  export let centerWhenEmpty = false;
  /**
   * Add the file picker + chips strip to the default composer shell. **Off by
   * default**, because the capability needs a host that consumes the files: an
   * `AparteClient` inlines them per its `rawFileInject` option, but if you drive
   * your own loop you must read `event.files` on `messageSent` — otherwise the file
   * the user deliberately attached is dropped in silence. No effect when you fill
   * the `composer` slot (drop `<aparte-composer-add-attachment>` and
   * `<aparte-composer-attachments>` in it yourself).
   */
  export let attachments = false;
  /** Active conversation id (loads/persists via the registered ConversationManager). */
  export let conversationId: string | null = null;
  /**
   * Instance {@link AparteConfigClass} for this chat. When set, aparté components
   * inside resolve THIS config instead of the global `AparteConfig` singleton, so
   * several independently-configured chats can coexist on one page. Omit for the
   * global config. Read once when the host mounts.
   */
  export let config: AparteConfigClass | undefined = undefined;

  const dispatch = createEventDispatcher<{
    /**
     * User submitted a message from the composer. It is **appended to the
     * thread automatically** (optimistic UI) before this fires — do NOT add it
     * again (uncontrolled → duplicates; controlled → mirror into your own
     * `messages`). For side-effects: scroll, analytics, send.
     */
    messageSent: AparteSendEventDetail;
    /** A custom bubble action (registerBubbleAction) was clicked — typed aparte-action. */
    action: AparteActionEventDetail;
    /** Active path changed (branch nav/edit/retry/streaming) — bind back to `messages`. */
    messagesChange: AparteMessage[];
    messageAppended: AparteMessage;
    /** The typing/"thinking" indicator toggled (the host flips it off on the first streamed token). */
    typingChange: boolean;
    conversationCreated: string;
  }>();

  // Generated client-side in onMount (below): during SSR this stays empty so the
  // server and first client render agree on the id — no hydration mismatch.
  let hostId = '';

  let rootRef: HTMLElement;
  let viewportRef: HTMLElement;
  let composerRef: HTMLElement;
  let internalMessages: AparteMessage[] = [...messages];
  let typingActive = isTyping;
  let host: AparteChatHost | null = null;
  let teardown: (() => void) | null = null;

  // Parent push → internal list (guarded against the host's own emit round-trip).
  let lastProp = messages;
  $: if (messages !== lastProp) {
    lastProp = messages;
    internalMessages = [...messages];
    if (messages.length === 0) host?.clearRenderCache();
  }

  // Controlled typing indicator (host may flip it off on the first token).
  let lastTyping = isTyping;
  $: if (isTyping !== lastTyping) { lastTyping = isTyping; typingActive = isTyping; }

  // Conversation id changes (initial value loaded by the host on bind).
  let lastConv = conversationId;
  $: if (conversationId !== lastConv) {
    lastConv = conversationId;
    void host?.setConversationId(conversationId ?? null);
  }

  // Reconcile bubbles after the rendered list changes (host queries the DOM).
  $: if (host && internalMessages) { void tick().then(() => host?.syncBubbles()); }

  // Composer attributes set imperatively (like Angular's `[attr.x]`): Svelte's
  // custom-element binding assigns to *properties*, but aparte-composer exposes
  // some of these (e.g. `placeholder`) as getter-only — assigning throws.
  function toggleAttr(el: HTMLElement, name: string, on: boolean, value: string) {
    if (on) el.setAttribute(name, value); else el.removeAttribute(name);
  }
  $: if (composerRef) {
    composerRef.setAttribute('target', hostId);
    composerRef.setAttribute('placeholder', placeholder);
    toggleAttr(composerRef, 'disabled', disabled, '');
    toggleAttr(composerRef, 'submit-on-enter', !submitOnEnter, 'false');
  }

  function handleSend(event: Event) {
    (viewportRef as unknown as { requestSmoothScroll?: () => void })?.requestSmoothScroll?.();
    dispatch('messageSent', (event as CustomEvent<AparteSendEventDetail>).detail);
  }

  // Custom bubble actions bubble to the root as `aparte-action` — dispatch typed.
  function handleAction(event: Event) {
    dispatch('action', (event as CustomEvent<AparteActionEventDetail>).detail);
  }

  onMount(() => {
    hostId = `aparte-chat-${crypto.randomUUID()}`;
    // Set the id imperatively (deterministic, like Angular's ngAfterViewInit) rather
    // than waiting on a reactive re-render of `id={hostId}`; the composer target
    // reactive block below picks up the same hostId.
    if (rootRef) rootRef.id = hostId;
    const binding: AparteChatHostBinding = {
      hostId,
      host: rootRef,
      viewport: viewportRef,
      getMessages: () => internalMessages,
      setMessages: (m) => { internalMessages = m as AparteMessage[]; },
      onMessagesChange: (m) => dispatch('messagesChange', m as AparteMessage[]),
      onMessageAppended: (m) => dispatch('messageAppended', m as AparteMessage),
      onTypingChange: (t) => { typingActive = t; dispatch('typingChange', t); },
      onStreamingChange: () => { /* exposed via isStreaming() */ },
      afterRender: (cb) => { void tick().then(cb); },
      resetComposer: () => (composerRef as unknown as { reset?: () => void })?.reset?.(),
    };
    host = new AparteChatHost(binding, {
      layoutTransitionMs,
      conversationId: conversationId ?? null,
      onConversationCreated: (id) => dispatch('conversationCreated', id),
      config,
    });
    teardown = host.bind();
    host.syncBubbles();
    rootRef?.addEventListener('aparte-action', handleAction);
  });

  onDestroy(() => {
    rootRef?.removeEventListener('aparte-action', handleAction);
    teardown?.();
    teardown = null;
    host = null;
  });

  // ── Imperative API (bind:this on the component) ──
  export function appendMessage(m: AparteMessage) { host?.appendMessage(m); }
  export function updateMessage(id: string, u: Partial<AparteMessage>) { host?.updateMessage(id, u); }
  export function updateLastMessage(content: string, options?: { append?: boolean }) {
    host?.updateLastMessage(content, options);
  }
  export function addSegment(segment: AparteSegment) { host?.addSegment(segment); }
  export function updateSegment(segmentId: string, updates: Partial<AparteSegment>) {
    host?.updateSegment(segmentId, updates);
  }
  export function removeSegment(segmentId: string) { host?.removeSegment(segmentId); }
  export function appendToSegment(segmentId: string, content: string) {
    host?.appendToSegment(segmentId, content);
  }
  export function getMessages(): AparteMessage[] { return host?.getMessages() ?? internalMessages; }
  export function clearMessages() { host?.clearMessages(); }
  export function addBranch(messageId: string): number { return host?.addBranch(messageId) ?? 0; }
  export function addSiblingOf(existingId: string, message: AparteMessage): string | null {
    return host?.addSiblingOf(existingId, message) ?? null;
  }
  export function truncateFrom(messageId: string) { host?.truncateFrom(messageId); }
  export function truncateResponsesAfter(userMessageId: string) {
    host?.truncateResponsesAfter(userMessageId);
  }
  export function injectTokenStream(messageId: string, tokens: AsyncIterable<string>): Promise<void> {
    return host?.streamTokens(messageId, tokens) ?? Promise.resolve();
  }
  export function stopTokenStream() { host?.stopTokenStream(); }
  export function setConversationId(id: string | null): Promise<void> {
    return host?.setConversationId(id) ?? Promise.resolve();
  }
  export function scrollToBottom() {
    (viewportRef as unknown as { scrollToBottom?: () => void })?.scrollToBottom?.();
  }
  /**
   * The `<aparte-chat-viewport>` element — for custom scroll handling, an
   * IntersectionObserver, etc. Same `getViewport()` accessor on all four
   * wrappers.
   */
  export function getViewport(): HTMLElement | null { return viewportRef ?? null; }
  export function focusInput() {
    (composerRef as unknown as { focus?: () => void })?.focus?.();
  }
  export function isStreaming(): boolean { return host?.isStreaming ?? false; }

  // Compile-time parity check: Svelte 4 can't generic-annotate `export function`s,
  // so this never-called factory type-checks that the exported surface matches the
  // canonical AparteChatImperativeApi. A dropped/mistyped method is a build error.
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  function _assertImperativeParity(): AparteChatImperativeApi {
    return {
      appendMessage, updateMessage, updateLastMessage, addSegment, updateSegment, removeSegment,
      appendToSegment, getMessages, clearMessages, addBranch, addSiblingOf, truncateFrom,
      truncateResponsesAfter, injectTokenStream, stopTokenStream, setConversationId,
      scrollToBottom, focusInput, isStreaming, getViewport,
    };
  }
</script>

<div
  class="aparte-chat-container"
  class:aparte-chat-container--auto-center={centerWhenEmpty}
  data-aparte-chat
  data-aparte-empty={centerWhenEmpty && internalMessages.length === 0 ? '' : null}
  id={hostId}
  bind:this={rootRef}
>
  <aparte-chat-viewport bind:this={viewportRef} framework-managed="">
    <!-- Welcome / placeholder shown inside the viewport while empty. -->
    {#if internalMessages.length === 0}
      <slot name="empty-state" />
    {/if}
    <!-- `bubble` slot renders your OWN element per message in place of
         <aparte-chat-bubble>; driven by the reactive list so it streams live. -->
    {#each internalMessages as m (m.id)}
      <slot name="bubble" message={m}>
        <aparte-chat-bubble
          message-id={m.id}
          data-role={m.role}
          timestamp={m.timestamp}
          content={m.content}
          streaming={isAwaitingReply(m) ? '' : null}
        />
      </slot>
    {/each}
    <aparte-chat-status visible={typingActive ? '' : null} text={typingText} />
  </aparte-chat-viewport>

  <!-- Content above the composer (banner, disclaimer, context chip). -->
  <slot name="above-composer" />

  <aparte-composer
    bind:this={composerRef}
    on:aparte-send={handleSend}
  >
    <!-- Custom composer via the `composer` slot; falls back to the default
         shell (input · send, plus the attachment primitives when `attachments` is
         set). Compose the headless aparte-composer-* primitives freely for a
         skin-specific layout. -->
    <slot name="composer">
      <div class="aparte-composer-shell">
        {#if attachments}<aparte-composer-attachments></aparte-composer-attachments>{/if}
        <div class="aparte-composer-row">
          {#if attachments}<aparte-composer-add-attachment></aparte-composer-add-attachment>{/if}
          <aparte-composer-input></aparte-composer-input>
          <aparte-composer-send></aparte-composer-send>
        </div>
        <!-- Footer slots (model selector, token counter…). The row is
             removed from view by .aparte-composer-footer:empty when unused. -->
        {#if $$slots['footer-left'] || $$slots['footer-center'] || $$slots['footer-right']}
          <div class="aparte-composer-footer">
            <slot name="footer-left" />
            <slot name="footer-center" />
            <slot name="footer-right" />
          </div>
        {/if}
      </div>
    </slot>
  </aparte-composer>
</div>

// packages/wrappers/vue/src/components/AparteChat.vue
<script setup lang="ts">
import { ref, watch, onMounted, onBeforeUnmount, nextTick, useId, toRaw } from 'vue';
import { AparteChatHost, isAwaitingReply, type AparteChatHostBinding, type AparteConfigClass, type AparteChatImperativeApi } from '@aparte/core';
import type { AparteMessage, AparteSegment, AparteSendEventDetail, AparteActionEventDetail } from '../types.js';

interface Props {
  /** Optional: omit for an uncontrolled chat (defaults to []); use `v-model:messages` to control. */
  messages?: AparteMessage[];
  placeholder?: string;
  disabled?: boolean;
  isTyping?: boolean;
  typingText?: string;
  /** When false, Shift+Enter submits and a bare Enter inserts a newline. */
  submitOnEnter?: boolean;
  /** Freeze viewport spacer recalculation for this many ms after a conv swap. */
  layoutTransitionMs?: number;
  /**
   * Opt in to the "centered composer when empty" layout: the composer sits
   * vertically centered with the `empty-state` slot above it while the list is
   * empty, then slides to the bottom on the first message (~0.3s). Off by
   * default — additive (adds the `--auto-center` modifier + a `data-aparte-empty`
   * attribute the shipped `aparte.css` recipe keys off).
   */
  centerWhenEmpty?: boolean;
  /**
   * Add the file picker + chips strip to the default composer shell. **Off by
   * default**, because the capability needs a host that consumes the files: an
   * `AparteClient` inlines them per its `rawFileInject` option, but if you drive
   * your own loop you must read `event.files` on `messageSent` — otherwise the file
   * the user deliberately attached is dropped in silence. No effect when you fill
   * the `composer` slot (drop `<aparte-composer-add-attachment>` and
   * `<aparte-composer-attachments>` in it yourself).
   */
  attachments?: boolean;
  /** Active conversation id (loads/persists via the registered ConversationManager). */
  conversationId?: string | null;
  /**
   * Instance {@link AparteConfigClass} for this chat. When set, aparté components
   * inside resolve THIS config instead of the global `AparteConfig` singleton, so
   * several independently-configured chats can coexist on one page. Omit for the
   * global config. Read once when the host mounts.
   */
  config?: AparteConfigClass;
}

const props = withDefaults(defineProps<Props>(), {
  messages: () => [],
  placeholder: 'Type a message...',
  disabled: false,
  isTyping: false,
  typingText: 'Assistant is thinking...',
  submitOnEnter: true,
  layoutTransitionMs: 0,
  centerWhenEmpty: false,
  attachments: false,
  conversationId: null,
});

const emit = defineEmits<{
  /**
   * User submitted a message from the composer. The message is **appended to
   * the thread automatically** (optimistic UI) before this fires — do NOT add
   * it again in the handler (uncontrolled → duplicates; controlled → mirror it
   * into your own `messages`). For side-effects: scroll, analytics, send.
   */
  messageSent: [event: AparteSendEventDetail];
  /** A custom bubble action (registerBubbleAction) was clicked — typed aparte-action. */
  action: [detail: AparteActionEventDetail];
  /** Active path changed (branch nav/edit/retry/streaming) — bind back to `messages`. */
  messagesChange: [messages: AparteMessage[]];
  /** Same payload as `messagesChange`, enabling `v-model:messages`. */
  'update:messages': [messages: AparteMessage[]];
  messageAppended: [message: AparteMessage];
  /** The typing/"thinking" indicator toggled (the host flips it off on the first streamed token). */
  typingChange: [isTyping: boolean];
  conversationCreated: [id: string];
}>();

// useId() (Vue 3.5+) is SSR-stable — server and client agree, no hydration mismatch.
const hostId = `aparte-chat-${useId()}`;
const rootRef = ref<HTMLElement>();
const viewportRef = ref<HTMLElement>();
const composerRef = ref<HTMLElement>();
const internalMessages = ref<AparteMessage[]>([...props.messages]);
const typingActive = ref(props.isTyping);

let host: AparteChatHost | null = null;
let teardown: (() => void) | null = null;

function onSend(e: Event) {
  (viewportRef.value as unknown as { requestSmoothScroll?: () => void })?.requestSmoothScroll?.();
  emit('messageSent', (e as CustomEvent<AparteSendEventDetail>).detail);
}

// Custom bubble actions bubble to the root as `aparte-action` — surface them typed.
function onAction(e: Event) {
  emit('action', (e as CustomEvent<AparteActionEventDetail>).detail);
}

onMounted(() => {
  const binding: AparteChatHostBinding = {
    hostId,
    host: rootRef.value as HTMLElement,
    viewport: viewportRef.value ?? null,
    getMessages: () => internalMessages.value,
    setMessages: (m) => { internalMessages.value = m as AparteMessage[]; },
    onMessagesChange: (m) => { emit('messagesChange', m as AparteMessage[]); emit('update:messages', m as AparteMessage[]); },
    onMessageAppended: (m) => emit('messageAppended', m as AparteMessage),
    onTypingChange: (t) => { typingActive.value = t; emit('typingChange', t); },
    onStreamingChange: () => { /* exposed via isStreaming() */ },
    afterRender: (cb) => { void nextTick(cb); },
    resetComposer: () => (composerRef.value as unknown as { reset?: () => void })?.reset?.(),
  };
  host = new AparteChatHost(binding, {
    layoutTransitionMs: props.layoutTransitionMs,
    conversationId: props.conversationId ?? null,
    onConversationCreated: (id) => emit('conversationCreated', id),
    // Unwrap Vue's reactive proxy: the config is a plain class with internal
    // Map registries the host/components must operate on directly, not through a
    // deep reactive proxy (which would wrap those Maps and break lookups).
    config: props.config ? toRaw(props.config) : undefined,
  });
  teardown = host.bind();
  host.syncBubbles();
  composerRef.value?.addEventListener('aparte-send', onSend);
  rootRef.value?.addEventListener('aparte-action', onAction);
});

onBeforeUnmount(() => {
  composerRef.value?.removeEventListener('aparte-send', onSend);
  rootRef.value?.removeEventListener('aparte-action', onAction);
  teardown?.();
  teardown = null;
  host = null;
});

// Parent push → internal list (guarded against the host's own emit round-trip).
watch(() => props.messages, (m) => {
  if (m === internalMessages.value) return;
  internalMessages.value = [...m];
  if (m.length === 0) host?.clearRenderCache();
});

// Reconcile bubbles after the rendered list changes (host queries the DOM).
watch(internalMessages, () => { void nextTick(() => host?.syncBubbles()); });

watch(() => props.isTyping, (t) => { typingActive.value = t; });
watch(() => props.conversationId, (id) => { void host?.setConversationId(id ?? null); });

// ── Imperative API (forwards to the host) ──
const appendMessage = (m: AparteMessage) => host?.appendMessage(m);
const updateMessage = (id: string, u: Partial<AparteMessage>) => host?.updateMessage(id, u);
const updateLastMessage = (c: string, o?: { append?: boolean }) => host?.updateLastMessage(c, o);
const addSegment = (s: AparteSegment) => host?.addSegment(s);
const updateSegment = (id: string, u: Partial<AparteSegment>) => host?.updateSegment(id, u);
const removeSegment = (id: string) => host?.removeSegment(id);
const appendToSegment = (id: string, c: string) => host?.appendToSegment(id, c);
const getMessages = () => host?.getMessages() ?? internalMessages.value;
const clearMessages = () => host?.clearMessages();
const addBranch = (id: string) => host?.addBranch(id) ?? 0;
const addSiblingOf = (id: string, m: AparteMessage) => host?.addSiblingOf(id, m) ?? null;
const truncateFrom = (id: string) => host?.truncateFrom(id);
const truncateResponsesAfter = (id: string) => host?.truncateResponsesAfter(id);
const injectTokenStream = (id: string, tokens: AsyncIterable<string>) =>
  host?.streamTokens(id, tokens) ?? Promise.resolve();
const stopTokenStream = () => host?.stopTokenStream();
const setConversationId = (id: string | null) => host?.setConversationId(id) ?? Promise.resolve();
const scrollToBottom = () => (viewportRef.value as unknown as { scrollToBottom?: () => void })?.scrollToBottom?.();
const focusInput = () => (composerRef.value as unknown as { focus?: () => void })?.focus?.();
const isStreaming = () => host?.isStreaming ?? false;

// `getViewport()` (not a raw `viewport` ref): the same accessor on all four
// wrappers — Svelte 4 can only expose functions, so the shared name is one.
const getViewport = () => viewportRef.value ?? null;

// `satisfies` makes a dropped or mistyped method a compile error — the canonical
// AparteChatImperativeApi is enforced here, not just aliased for consumers.
defineExpose({
  appendMessage, updateMessage, updateLastMessage, addSegment, updateSegment, removeSegment,
  appendToSegment, getMessages, clearMessages, addBranch, addSiblingOf, truncateFrom,
  truncateResponsesAfter, injectTokenStream, stopTokenStream, setConversationId,
  scrollToBottom, focusInput, isStreaming, getViewport,
} satisfies AparteChatImperativeApi);
</script>

<template>
  <div
    :class="['aparte-chat-container', { 'aparte-chat-container--auto-center': centerWhenEmpty }]"
    data-aparte-chat
    :data-aparte-empty="centerWhenEmpty && internalMessages.length === 0 ? '' : null"
    :id="hostId"
    ref="rootRef"
  >
    <aparte-chat-viewport ref="viewportRef" framework-managed="">
      <!-- Welcome / placeholder shown inside the viewport while there are no
           messages (a real empty-state region). -->
      <slot v-if="internalMessages.length === 0" name="empty-state" />
      <!-- `bubble` scoped slot renders your OWN element per message in place of
           <aparte-chat-bubble>; driven by the reactive list so it streams live. -->
      <template v-for="m in internalMessages" :key="m.id">
        <slot name="bubble" :message="m">
          <aparte-chat-bubble
            :message-id="m.id"
            :data-role="m.role"
            :timestamp="m.timestamp"
            :content="m.content"
            :streaming="isAwaitingReply(m) ? '' : null"
          />
        </slot>
      </template>
      <aparte-chat-status :visible="typingActive ? '' : null" :text="typingText" />
    </aparte-chat-viewport>

    <!-- Content above the composer (banner, disclaimer, context chip). -->
    <slot name="above-composer" />

    <!-- `.attr` forces attribute-setting: core's <aparte-composer> exposes
         `placeholder`/`disabled` as getter-only accessors, so Vue's default
         property-set (it prefers props on custom elements) would throw and the
         value would silently never apply. -->
    <aparte-composer
      ref="composerRef"
      :target="hostId"
      :placeholder.attr="placeholder"
      :disabled.attr="disabled ? '' : null"
      :submit-on-enter="submitOnEnter ? null : 'false'"
    >
      <!-- Custom composer via the `composer` slot; falls back to the default
           shell (input · send, plus the attachment primitives when `attachments`
           is set). Compose the headless aparte-composer-* primitives freely for a
           skin-specific layout. -->
      <slot name="composer">
        <div class="aparte-composer-shell">
          <aparte-composer-attachments v-if="attachments"></aparte-composer-attachments>
          <div class="aparte-composer-row">
            <aparte-composer-add-attachment v-if="attachments"></aparte-composer-add-attachment>
            <aparte-composer-input></aparte-composer-input>
            <aparte-composer-send></aparte-composer-send>
          </div>
          <!-- Footer slots (model selector, token counter…). The row is
               removed from view by .aparte-composer-footer:empty when unused. -->
          <div
            v-if="$slots['footer-left'] || $slots['footer-center'] || $slots['footer-right']"
            class="aparte-composer-footer"
          >
            <slot name="footer-left" />
            <slot name="footer-center" />
            <slot name="footer-right" />
          </div>
        </div>
      </slot>
    </aparte-composer>
  </div>
</template>
