// packages/wrappers/react/src/components/AparteUi.tsx
import { useEffect, useRef, forwardRef, useImperativeHandle } from 'react';

export interface AparteUiProps {
    /** The custom element tag name (e.g. 'aparte-chat-input'). */
    name: string;
    /** Props to apply. Keys starting with `--` become CSS variables. */
    props?: Record<string, unknown>;
    /** Emits a forwarded custom event from the underlying Web Component. */
    onElementEvent?: (event: CustomEvent) => void;
    /**
     * Which custom events to forward through `onElementEvent`. Defaults to the
     * interactive aparté surface ({@link DEFAULT_EVENTS}); pass your own list to
     * listen to other events (e.g. `['aparte:composer-change']` for attachments).
     */
    events?: string[];
}

export interface AparteUiHandle {
    getElement: <T extends HTMLElement = HTMLElement>() => T | null;
    callMethod: <T = unknown>(methodName: string, ...args: unknown[]) => T | undefined;
}

/** The custom events aparté elements actually dispatch (verified against core). */
const DEFAULT_EVENTS = [
    'aparte-send',
    'aparte:action',
    'aparte:retry',
    'aparte:edit',
    'aparte:branch-navigate',
    'aparte:composer-change',
    'aparte:path-changed',
];

/**
 * aparté elements are **attribute-driven** (`observedAttributes`): assigning a
 * property is either a silent no-op (nothing observes it) or throws outright on a
 * getter-only accessor — `<aparte-composer>`'s `placeholder`/`disabled` are exactly
 * that. So primitives go through `setAttribute`; only values an attribute cannot
 * carry (objects, functions) are handed over as properties.
 */
function applyProps(el: HTMLElement, props: Record<string, unknown>): void {
    for (const [key, value] of Object.entries(props)) {
        if (key.startsWith('--')) {
            el.style.setProperty(key, String(value));
        } else if (key.startsWith('on') && typeof value === 'function') {
            // Event handlers belong on `events` + onElementEvent, not here.
        } else if (value === null || value === undefined || value === false) {
            el.removeAttribute(key);
        } else if (value === true) {
            el.setAttribute(key, '');
        } else if (typeof value === 'object' || typeof value === 'function') {
            (el as unknown as Record<string, unknown>)[key] = value;
        } else {
            el.setAttribute(key, String(value));
        }
    }
}

/**
 * Universal pass-through proxy: dynamically mounts any `aparte-*` Web Component so
 * you don't need a dedicated React wrapper per element. React equivalent of
 * Angular's `AparteUiComponent`.
 *
 * @example
 * <AparteUi name="aparte-chat-input" props={{ placeholder: 'Ask…', '--glow-speed': '4s' }} onElementEvent={onEvent} />
 */
export const AparteUi = forwardRef<AparteUiHandle, AparteUiProps>(function AparteUi(
    { name, props = {}, onElementEvent, events },
    ref,
) {
    const hostRef = useRef<HTMLSpanElement>(null);
    const elRef = useRef<HTMLElement | null>(null);
    const cbRef = useRef(onElementEvent);
    cbRef.current = onElementEvent;

    const evts = events ?? DEFAULT_EVENTS;
    const evtsKey = evts.join('|');

    // (Re)create the element when `name` (or the forwarded event set) changes.
    useEffect(() => {
        const host = hostRef.current;
        if (!host) return;
        const el = document.createElement(name);
        elRef.current = el;
        const cleanups: Array<() => void> = [];
        for (const ev of evtsKey.split('|').filter(Boolean)) {
            const listener = (e: Event) => cbRef.current?.(e as CustomEvent);
            el.addEventListener(ev, listener);
            cleanups.push(() => el.removeEventListener(ev, listener));
        }
        host.appendChild(el);
        return () => {
            for (const c of cleanups) c();
            el.remove();
            elRef.current = null;
        };
    }, [name, evtsKey]);

    // Apply props whenever they change.
    useEffect(() => {
        if (elRef.current) applyProps(elRef.current, props);
    }, [props]);

    useImperativeHandle(ref, (): AparteUiHandle => ({
        getElement: () => elRef.current as never,
        callMethod: (methodName, ...args) => {
            const fn = (elRef.current as unknown as Record<string, unknown>)?.[methodName];
            return typeof fn === 'function'
                ? (fn as (...a: unknown[]) => unknown).apply(elRef.current, args) as never
                : undefined;
        },
    }), []);

    return <span ref={hostRef} style={{ display: 'contents' }} />;
});

AparteUi.displayName = 'AparteUi';

// packages/wrappers/vue/src/components/AparteUi.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onBeforeUnmount, toRaw } from 'vue';

const p = defineProps<{
  /** The custom element tag name (e.g. 'aparte-chat-input'). */
  name: string;
  /** Props to apply. Keys starting with `--` become CSS variables. */
  props?: Record<string, unknown>;
  /**
   * Which custom events to forward through `elementEvent`. Defaults to the
   * interactive aparté surface (DEFAULT_EVENTS); pass your own list to listen to
   * other events (e.g. ['aparte:composer-change'] for attachments).
   */
  events?: string[];
}>();

const emit = defineEmits<{ elementEvent: [event: CustomEvent] }>();

/** The custom events aparté elements actually dispatch (verified against core). */
const DEFAULT_EVENTS = [
  'aparte-send',
  'aparte:action',
  'aparte:retry',
  'aparte:edit',
  'aparte:branch-navigate',
  'aparte:composer-change',
  'aparte:path-changed',
];

// A stable key so a fresh inline `:events` array doesn't thrash the element —
// only a real change to the event names rebinds (mirrors React's evtsKey).
const evtsKey = computed(() => (p.events ?? DEFAULT_EVENTS).join('|'));

const hostRef = ref<HTMLElement>();
let el: HTMLElement | null = null;
let cleanups: Array<() => void> = [];

/**
 * aparté elements are **attribute-driven** (`observedAttributes`): assigning a
 * property is either a silent no-op (nothing observes it) or throws outright on a
 * getter-only accessor — `<aparte-composer>`'s `placeholder`/`disabled` are exactly
 * that. So primitives go through `setAttribute`; only values an attribute cannot
 * carry (objects, functions) are handed over as properties.
 */
function applyProps() {
  if (!el) return;
  for (const [key, value] of Object.entries(p.props ?? {})) {
    if (key.startsWith('--')) el.style.setProperty(key, String(value));
    else if (key.startsWith('on') && typeof value === 'function') {
      // Event handlers belong on `events` + the elementEvent emit, not here.
    } else if (value === null || value === undefined || value === false) el.removeAttribute(key);
    else if (value === true) el.setAttribute(key, '');
    else if (typeof value === 'object' || typeof value === 'function') {
      // Unwrap Vue's reactive proxy before handing it to a plain custom element:
      // a deep proxy wraps Maps/class internals and breaks them (same reason
      // <AparteChat> passes `toRaw(config)` to the host).
      (el as unknown as Record<string, unknown>)[key] = toRaw(value);
    } else el.setAttribute(key, String(value));
  }
}

function create() {
  if (!hostRef.value) return;
  el = document.createElement(p.name);
  applyProps();
  for (const ev of evtsKey.value.split('|').filter(Boolean)) {
    const listener = (e: Event) => emit('elementEvent', e as CustomEvent);
    el.addEventListener(ev, listener);
    cleanups.push(() => el?.removeEventListener(ev, listener));
  }
  hostRef.value.appendChild(el);
}

function destroy() {
  for (const c of cleanups) c();
  cleanups = [];
  el?.remove();
  el = null;
}

onMounted(create);
onBeforeUnmount(destroy);
watch(() => p.name, () => { destroy(); create(); });
watch(evtsKey, () => { destroy(); create(); });
watch(() => p.props, applyProps, { deep: true });

defineExpose({
  getElement: () => el,
  callMethod: (methodName: string, ...args: unknown[]) => {
    const fn = (el as unknown as Record<string, unknown>)?.[methodName];
    return typeof fn === 'function' ? (fn as (...a: unknown[]) => unknown).apply(el, args) : undefined;
  },
});
</script>

<template>
  <span ref="hostRef" style="display: contents"></span>
</template>
