// packages/wrappers/react/src/components/AparteUi.tsx
import { useEffect, useRef, forwardRef, useImperativeHandle } from 'react';

export interface AparteUiProps {
    /** The custom element tag name (e.g. 'aparte-chat-input'). */
    name: string;
    /** Props to apply. Keys starting with `--` become CSS variables. */
    props?: Record<string, unknown>;
    /** Emits a forwarded custom event from the underlying Web Component. */
    onElementEvent?: (event: CustomEvent) => void;
    /**
     * Which custom events to forward through `onElementEvent`. Defaults to the
     * interactive aparté surface ({@link DEFAULT_EVENTS}); pass your own list to
     * listen to other events (e.g. `['aparte:composer-change']` for attachments).
     */
    events?: string[];
}

export interface AparteUiHandle {
    getElement: <T extends HTMLElement = HTMLElement>() => T | null;
    callMethod: <T = unknown>(methodName: string, ...args: unknown[]) => T | undefined;
}

/** The custom events aparté elements actually dispatch (verified against core). */
const DEFAULT_EVENTS = [
    'aparte-send',
    'aparte:action',
    'aparte:retry',
    'aparte:edit',
    'aparte:branch-navigate',
    'aparte:composer-change',
    'aparte:path-changed',
];

/**
 * aparté elements are **attribute-driven** (`observedAttributes`): assigning a
 * property is either a silent no-op (nothing observes it) or throws outright on a
 * getter-only accessor — `<aparte-composer>`'s `placeholder`/`disabled` are exactly
 * that. So primitives go through `setAttribute`; only values an attribute cannot
 * carry (objects, functions) are handed over as properties.
 */
function applyProps(el: HTMLElement, props: Record<string, unknown>): void {
    for (const [key, value] of Object.entries(props)) {
        if (key.startsWith('--')) {
            el.style.setProperty(key, String(value));
        } else if (key.startsWith('on') && typeof value === 'function') {
            // Event handlers belong on `events` + onElementEvent, not here.
        } else if (value === null || value === undefined || value === false) {
            el.removeAttribute(key);
        } else if (value === true) {
            el.setAttribute(key, '');
        } else if (typeof value === 'object' || typeof value === 'function') {
            (el as unknown as Record<string, unknown>)[key] = value;
        } else {
            el.setAttribute(key, String(value));
        }
    }
}

/**
 * Universal pass-through proxy: dynamically mounts any `aparte-*` Web Component so
 * you don't need a dedicated React wrapper per element. React equivalent of
 * Angular's `AparteUiComponent`.
 *
 * @example
 * <AparteUi name="aparte-chat-input" props={{ placeholder: 'Ask…', '--glow-speed': '4s' }} onElementEvent={onEvent} />
 */
export const AparteUi = forwardRef<AparteUiHandle, AparteUiProps>(function AparteUi(
    { name, props = {}, onElementEvent, events },
    ref,
) {
    const hostRef = useRef<HTMLSpanElement>(null);
    const elRef = useRef<HTMLElement | null>(null);
    const cbRef = useRef(onElementEvent);
    cbRef.current = onElementEvent;

    const evts = events ?? DEFAULT_EVENTS;
    const evtsKey = evts.join('|');

    // (Re)create the element when `name` (or the forwarded event set) changes.
    useEffect(() => {
        const host = hostRef.current;
        if (!host) return;
        const el = document.createElement(name);
        elRef.current = el;
        const cleanups: Array<() => void> = [];
        for (const ev of evtsKey.split('|').filter(Boolean)) {
            const listener = (e: Event) => cbRef.current?.(e as CustomEvent);
            el.addEventListener(ev, listener);
            cleanups.push(() => el.removeEventListener(ev, listener));
        }
        host.appendChild(el);
        return () => {
            for (const c of cleanups) c();
            el.remove();
            elRef.current = null;
        };
    }, [name, evtsKey]);

    // Apply props whenever they change.
    useEffect(() => {
        if (elRef.current) applyProps(elRef.current, props);
    }, [props]);

    useImperativeHandle(ref, (): AparteUiHandle => ({
        getElement: () => elRef.current as never,
        callMethod: (methodName, ...args) => {
            const fn = (elRef.current as unknown as Record<string, unknown>)?.[methodName];
            return typeof fn === 'function'
                ? (fn as (...a: unknown[]) => unknown).apply(elRef.current, args) as never
                : undefined;
        },
    }), []);

    return <span ref={hostRef} style={{ display: 'contents' }} />;
});

AparteUi.displayName = 'AparteUi';

// packages/wrappers/angular/src/lib/aparte-ui.component.ts
import {
    Component,
    CUSTOM_ELEMENTS_SCHEMA,
    ElementRef,
    OnChanges,
    OnDestroy,
    AfterViewInit,
    SimpleChanges,
    ChangeDetectionStrategy,
    Input,
    output,
    Renderer2,
    inject
} from '@angular/core';

/** The custom events aparté elements actually dispatch (verified against core). */
const DEFAULT_EVENTS = [
    'aparte-send',
    'aparte:action',
    'aparte:retry',
    'aparte:edit',
    'aparte:branch-navigate',
    'aparte:composer-change',
    'aparte:path-changed',
];

/**
 * AparteUiComponent - Universal UI Proxy
 *
 * A pass-through proxy component that dynamically injects any aparté
 * Web Component, so you don't need a dedicated Angular wrapper per element.
 *
 * @example
 * ```html
 * <aparte-ui
 *   name="aparte-chat-input"
 *   [props]="{
 *     placeholder: 'Ask anything...',
 *     '--glow-opacity': '1',
 *     '--glow-speed': '4s'
 *   }"
 *   (elementEvent)="onEvent($event)"
 * />
 * ```
 *
 * @description
 * - Keys starting with `--` are applied as CSS Variables
 * - Other keys are set as DOM properties on the element
 * - The events in `events` (default: {@link DEFAULT_EVENTS}) bubble up via `elementEvent`
 */
@Component({
    selector: 'aparte-ui',
    standalone: true,
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: `<ng-container></ng-container>`,
    styles: [`
    :host {
      display: contents;
    }
  `]
})
export class AparteUiComponent implements AfterViewInit, OnChanges, OnDestroy {
    private readonly renderer = inject(Renderer2);
    private readonly hostEl = inject(ElementRef);

    // ─────────────────────────────────────────────────────────────
    // Inputs
    // ─────────────────────────────────────────────────────────────

    /** The custom element tag name (e.g., 'aparte-chat-input') */
    @Input({ required: true }) name!: string;

    /** Properties to pass to the element. Keys starting with '--' are CSS vars */
    @Input() props: Record<string, unknown> = {};

    /**
     * Which custom events to forward through `elementEvent`. Defaults to the
     * interactive aparté surface ({@link DEFAULT_EVENTS}); pass your own list to
     * listen to other events (e.g. `['aparte:composer-change']` for attachments).
     */
    @Input() events?: string[];

    // ─────────────────────────────────────────────────────────────
    // Outputs
    // ─────────────────────────────────────────────────────────────

    /** Emits a forwarded custom event from the underlying Web Component */
    readonly elementEvent = output<CustomEvent>();

    // ─────────────────────────────────────────────────────────────
    // Internal State
    // ─────────────────────────────────────────────────────────────

    /** The dynamically created Web Component element */
    private element: HTMLElement | null = null;

    /** Cleanup functions for event listeners */
    private eventCleanups: (() => void)[] = [];

    /** Joined key of the bound event set, so a fresh inline `[events]` array
     *  doesn't thrash the element — only a real change rebinds. */
    private lastEventsKey = '';

    // ─────────────────────────────────────────────────────────────
    // Lifecycle
    // ─────────────────────────────────────────────────────────────

    ngAfterViewInit(): void {
        this.createElement();
    }

    ngOnChanges(changes: SimpleChanges): void {
        // Recreate the element when `name` (or the forwarded event set) changes.
        const nameChanged = !!changes['name'] && !changes['name'].firstChange;
        const eventsChanged =
            !!changes['events'] &&
            !changes['events'].firstChange &&
            this.eventsKey() !== this.lastEventsKey;

        if (nameChanged || eventsChanged) {
            this.destroyElement();
            this.createElement();
        }

        // If props changed, update them
        if (changes['props'] && this.element) {
            this.applyProps();
        }
    }

    ngOnDestroy(): void {
        this.destroyElement();
    }

    // ─────────────────────────────────────────────────────────────
    // Element Management
    // ─────────────────────────────────────────────────────────────

    private eventsKey(): string {
        return (this.events ?? DEFAULT_EVENTS).join('|');
    }

    private createElement(): void {
        if (!this.name) return;

        // Create the custom element
        this.element = this.renderer.createElement(this.name);

        // Apply initial props
        this.applyProps();

        // Setup event listeners
        this.setupEventListeners();

        // Append to host (not container, to avoid extra wrapper)
        this.renderer.appendChild(this.hostEl.nativeElement, this.element);
    }

    private destroyElement(): void {
        // Cleanup event listeners
        this.eventCleanups.forEach(cleanup => cleanup());
        this.eventCleanups = [];

        // Remove element
        if (this.element && this.element.parentNode) {
            this.renderer.removeChild(this.hostEl.nativeElement, this.element);
        }
        this.element = null;
    }

    /**
     * aparté elements are **attribute-driven** (`observedAttributes`): assigning a
     * property is either a silent no-op (nothing observes it) or throws outright on
     * a getter-only accessor — `<aparte-composer>`'s `placeholder`/`disabled` are
     * exactly that. So primitives go through `setAttribute`; only values an
     * attribute cannot carry (objects, functions) are handed over as properties.
     */
    private applyProps(): void {
        if (!this.element) return;

        Object.entries(this.props).forEach(([key, value]) => {
            if (key.startsWith('--')) {
                // CSS Variable: apply to element style
                this.element!.style.setProperty(key, String(value));
            } else if (key.startsWith('on') && typeof value === 'function') {
                // Event handler: belongs on `events` + (elementEvent), not here
            } else if (value === null || value === undefined || value === false) {
                this.element!.removeAttribute(key);
            } else if (value === true) {
                this.element!.setAttribute(key, '');
            } else if (typeof value === 'object' || typeof value === 'function') {
                // Not serialisable to an attribute — hand it over as a property.
                // eslint-disable-next-line @typescript-eslint/no-explicit-any
                (this.element as any)[key] = value;
            } else {
                this.element!.setAttribute(key, String(value));
            }
        });
    }

    private setupEventListeners(): void {
        if (!this.element) return;

        this.lastEventsKey = this.eventsKey();
        (this.events ?? DEFAULT_EVENTS).forEach(eventName => {
            const listener = (event: Event) => {
                this.elementEvent.emit(event as CustomEvent);
            };

            this.element!.addEventListener(eventName, listener);
            this.eventCleanups.push(() => {
                this.element?.removeEventListener(eventName, listener);
            });
        });
    }

    // ─────────────────────────────────────────────────────────────
    // Public API
    // ─────────────────────────────────────────────────────────────

    /** Get the underlying Web Component element */
    getElement<T extends HTMLElement = HTMLElement>(): T | null {
        return this.element as T | null;
    }

    /** Call a method on the underlying element */
    callMethod<T = unknown>(methodName: string, ...args: unknown[]): T | undefined {
        if (!this.element) return undefined;

        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const method = (this.element as any)[methodName];
        if (typeof method === 'function') {
            return method.apply(this.element, args) as T;
        }
        return undefined;
    }
}
