// packages/wrappers/angular/src/lib/aparte-chat.component.ts
import {
    Component,
    CUSTOM_ELEMENTS_SCHEMA,
    ElementRef,
    OnDestroy,
    ViewChild,
    QueryList,
    ViewChildren,
    output,
    signal,
    computed,
    ChangeDetectionStrategy,
    AfterViewInit,
    Input,
    TemplateRef,
    inject,
    effect,
    booleanAttribute,
    numberAttribute,
} from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import { Observable } from 'rxjs';
import type {
    AparteMessage,
    AparteSegment,
    AparteSendEventDetail,
    AparteChatHostBinding,
    AparteConfig,
    AparteActionEventDetail,
    AparteChatImperativeApi,
} from '@aparte/core';
import { AparteChatHost, isAwaitingReply, uuid } from '@aparte/core';

/**
 * AparteChatComponent — Angular 19 Wrapper
 *
 * Standalone component wrapping aparté Web Components with Angular Signals.
 * The streaming / branch-navigation / host-method orchestration (orphan-stream
 * guard, lifecycle tracking, conversation lifecycle, bubble reconciliation)
 * lives in the framework-agnostic `AparteChatHost` from `@aparte/core`; this
 * component only owns the Angular-idiomatic surface (signals, template, DI) and
 * binds the host over its `messages` signal.
 */
@Component({
    selector: 'aparte-chat',
    standalone: true,
    imports: [NgTemplateOutlet],
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    changeDetection: ChangeDetectionStrategy.OnPush,
    // This selector is ALSO core's `<aparte-chat>` custom element, so the host gets
    // upgraded by core on insert. `framework-managed` tells that shell to keep its
    // hands off: THIS component renders the viewport + composer and drives them
    // through AparteChatHost. Without it, core injects its default composition
    // underneath ours (its own check can't see our children — they render later).
    host: { 'framework-managed': '' },
    template: `
    <div
      class="aparte-chat-container"
      [class.aparte-chat-container--auto-center]="centerWhenEmpty()"
      [attr.overlay-composer]="overlayComposer() ? '' : null"
      [attr.data-aparte-empty]="centerWhenEmpty() && messages().length === 0 ? '' : null"
    >
      <aparte-chat-viewport #viewport framework-managed="">
        @if (messages().length === 0) {
          <!-- Welcome / placeholder shown inside the viewport while empty. -->
          <ng-content select="[slot='empty-state']"></ng-content>
        }
        @for (message of messages(); track message.id) {
          @if (bubbleTemplate) {
            <!-- Render your OWN element per message; driven by the reactive
                 messages() signal so it streams live. -->
            <ng-container
              [ngTemplateOutlet]="bubbleTemplate"
              [ngTemplateOutletContext]="{ $implicit: message }"
            ></ng-container>
          } @else {
            <aparte-chat-bubble
              #bubble
              [attr.message-id]="message.id"
              [attr.data-role]="message.role"
              [attr.data-kind]="message.compaction ? 'compaction' : null"
              [attr.timestamp]="message.timestamp"
              [attr.content]="message.content"
              [attr.streaming]="awaitingReply(message) ? '' : null"
            ></aparte-chat-bubble>
          }
        }
        <aparte-chat-status
          [attr.visible]="isTyping() ? '' : null"
          [attr.text]="typingText()"
        ></aparte-chat-status>
      </aparte-chat-viewport>

      <!-- The presenter for a request to the human (approval gate, ask_user…).
           Renders nothing until something asks; on by default as in <aparte-chat>. -->
      @if (elicitation()) {
        <aparte-elicitation></aparte-elicitation>
      }

      <ng-content select="[slot='above-composer']"></ng-content>

      <aparte-composer
        #input
        [attr.placeholder]="placeholder()"
        [attr.disabled]="disabled() ? '' : null"
        [attr.submit-on-enter]="submitOnEnter() ? null : 'false'"
        (aparte-send)="onAparteSend($event)"
      >
        <!-- Custom composer via [slot='composer']; falls back to the default
             shell (input · send + footer slots, plus the attachment primitives
             when the attachments input is set). Project your own
             aparte-composer-* layout for a skin-specific composer. -->
        <ng-content select="[slot='composer']">
          <div class="aparte-composer-shell">
            @if (attachments()) {
              <aparte-composer-attachments></aparte-composer-attachments>
            }
            <div class="aparte-composer-row">
              @if (attachments()) {
                <aparte-composer-add-attachment></aparte-composer-add-attachment>
              }
              <aparte-composer-input></aparte-composer-input>
              <aparte-composer-send></aparte-composer-send>
            </div>
            <!-- The composer's bottom row. ONE slot: placement is the DOM order of
                 what you project, and margin-inline-start:auto pushes a control to the
                 end (a logical property, so it reads correctly in RTL).
                 Angular cannot test whether anything projects into an ng-content, so
                 unlike the other three wrappers the element is always rendered -- but it
                 declares itself data-empty when nothing lands in it, and the stylesheet
                 hides it then. The guarantee no longer depends on Angular stripping
                 template whitespace. -->
            <aparte-composer-toolbar>
              <ng-content select="[slot='toolbar']"></ng-content>
            </aparte-composer-toolbar>
          </div>
        </ng-content>
      </aparte-composer>
    </div>
  `,
    styles: [`
    :host {
      display: block;
      width: 100%;
      height: 100%;
    }

    .aparte-chat-container {
      display: flex;
      flex-direction: column;
      height: 100%;
      width: 100%;
      overflow: hidden;
    }

    aparte-chat-viewport {
      flex: 1;
      min-height: 0;
    }

    aparte-composer {
      flex-shrink: 0;
    }
  `]
})
export class AparteChatComponent implements AfterViewInit, OnDestroy, AparteChatImperativeApi {
    constructor() {
        // Reactive effect to reconcile bubbles when the messages signal updates.
        // Debounced with requestAnimationFrame so rapid token bursts only trigger
        // one sync per paint frame instead of N syncs for N tokens.
        effect(() => {
            const msgs = this.messages();
            if (msgs.length > 0) {
                if (this._syncRafId !== null) return;
                this._syncRafId = requestAnimationFrame(() => {
                    this._syncRafId = null;
                    this._host?.syncBubbles();
                });
            }
        });
    }

    private elementRef = inject(ElementRef);

    /**
     * Template bridge to core's shared `isAwaitingReply` (an Angular template can't
     * call an imported function). One rule for the four wrappers and core itself,
     * so "is this bubble in flight" can't drift between them.
     */
    readonly awaitingReply = isAwaitingReply;

    // ── Input Signals ────────────────────────────────────────────────────────

    /** Messages to display */
    @Input('messages') set messagesInput(val: AparteMessage[]) {
        this.messages.set(val);
        // When messages are cleared (new conversation), reset the host's render cache
        // so the next conversation starts clean — same as React/Vue/Svelte do. (The
        // viewport's own clearMessages() is @deprecated in core and only clears its
        // repo; the host's clearAll() path already owns the real teardown.)
        if (val.length === 0) this._host?.clearRenderCache();
    }
    readonly messages = signal<AparteMessage[]>([]);

    /** Input placeholder text */
    @Input('placeholder') set placeholderInput(val: string) { this.placeholder.set(val); }
    readonly placeholder = signal<string>('Type a message...');

    /** Whether the input is disabled */
    @Input({ alias: 'disabled', transform: booleanAttribute }) set disabledInput(val: boolean) { this.disabled.set(val); }
    readonly disabled = signal<boolean>(false);

    /** When false, Shift+Enter submits and a bare Enter inserts a newline. */
    @Input({ alias: 'submitOnEnter', transform: booleanAttribute }) set submitOnEnterInput(val: boolean) { this.submitOnEnter.set(val); }
    readonly submitOnEnter = signal<boolean>(true);

    /**
     * Opt in to the "centered composer when empty" layout: the composer sits
     * vertically centered with the `[slot='empty-state']` content above it while
     * the list is empty, then slides to the bottom on the first message (~0.3s).
     * Off by default — additive (adds the `--auto-center` modifier + a
     * `data-aparte-empty` attribute the shipped `aparte.css` recipe keys off).
     */
    @Input({ alias: 'centerWhenEmpty', transform: booleanAttribute }) set centerWhenEmptyInput(val: boolean) { this.centerWhenEmpty.set(val); }
    readonly centerWhenEmpty = signal<boolean>(false);

    /**
     * Overlay the composer on the transcript (the ChatGPT anatomy): the scroll
     * surface spans the whole column, the scrollbar runs edge to edge, and the
     * composer floats over it. Bound on the INNER `.aparte-chat-container` — that
     * div is this wrapper's shell (the viewport is its child, not the host's), and
     * core's recipe and the viewport's measurement both key on the attribute
     * there. Read when the viewport mounts.
     */
    @Input({ alias: 'overlayComposer', transform: booleanAttribute }) set overlayComposerInput(val: boolean) { this.overlayComposer.set(val); }
    readonly overlayComposer = signal<boolean>(false);

    /**
     * Add the file picker + chips strip to the default composer shell. **Off by
     * default**, because the capability needs a host that consumes the files: an
     * `AparteClient` inlines them per its `rawFileInject` option, but if you drive
     * your own loop you must read `event.files` on `(messageSent)` — otherwise the
     * file the user deliberately attached is dropped in silence. No effect when you
     * project a `[slot='composer']` (drop `<aparte-composer-add-attachment>` and
     * `<aparte-composer-attachments>` in it yourself).
     */
    @Input({ alias: 'attachments', transform: booleanAttribute }) set attachmentsInput(val: boolean) { this.attachments.set(val); }
    readonly attachments = signal<boolean>(false);

    /**
     * Render the `<aparte-elicitation>` presenter inside the host — on by default, as
     * it is in `<aparte-chat>`: the built-in approval gate and `requestUserInput()`
     * ask through it, and it renders nothing until something asks. Set it to `false`
     * when you mount a presenter of your own (`setElicitationPresenter`) or place the
     * element yourself.
     */
    @Input({ alias: 'elicitation', transform: booleanAttribute }) set elicitationInput(val: boolean) { this.elicitation.set(val); }
    readonly elicitation = signal<boolean>(true);

    /** Whether the assistant is currently typing/streaming */
    @Input({ alias: 'isTyping', transform: booleanAttribute }) set isTypingInput(val: boolean) { this.isTyping.set(val); }
    readonly isTyping = signal<boolean>(false);

    /** Text to show in the typing status */
    @Input('typingText') set typingTextInput(val: string) { this.typingText.set(val); }
    readonly typingText = signal<string>('Assistant is thinking...');

    /** Duration in ms to freeze spacer recalculation after a conversation swap. */
    @Input({ alias: 'layoutTransitionMs', transform: numberAttribute }) layoutTransitionMs = 0;

    /**
     * Active conversation id. When provided, the host attaches an
     * `AparteConversationController` that loads/persists messages via the
     * `AparteConversationManager` registered in `aparteGlobalConfig`. Setting a different id
     * mid-stream aborts the previous request; `null` deselects.
     */
    @Input('conversationId') set conversationIdInput(val: string | null | undefined) {
        const next = val ?? null;
        if (next === this._conversationId) return;
        this._conversationId = next;
        if (this._host) void this._host.setConversationId(next);
    }
    private _conversationId: string | null = null;

    /**
     * Instance {@link AparteConfig} for this chat. When set, aparté components
     * inside resolve THIS config instead of `aparteGlobalConfig`, so
     * several independently-configured chats can coexist on one page. Omit for the
     * global config. Read once in `ngAfterViewInit` when the host is created.
     */
    @Input() config?: AparteConfig;

    /**
     * Render your OWN element per message in place of `<aparte-chat-bubble>`.
     * Opt-in — provide a `<ng-template let-message>` and pass its ref. Driven by
     * the reactive `messages()` signal, so it updates live during streaming.
     * The built-in action bar (retry/edit/branch) belongs to the native bubble;
     * a custom bubble owns whatever it wires.
     * @example
     * <aparte-chat [bubbleTemplate]="tpl" />
     * <ng-template #tpl let-message>{{ message.content }}</ng-template>
     */
    @Input() bubbleTemplate?: TemplateRef<{ $implicit: AparteMessage }>;

    // ── Outputs ────────────────────────────────────────────────────────────

    /**
     * User submitted a message from the composer. It is **appended to the thread
     * automatically** (optimistic UI) before this fires — do NOT add it again in
     * the handler (uncontrolled → duplicates; controlled → mirror it into your
     * own `[messages]`). For side-effects: scroll, analytics, send.
     */
    readonly messageSent = output<AparteSendEventDetail>();
    /**
     * Emitted when a custom bubble action (registered via
     * `aparteGlobalConfig.registerAction` with `zones: ['bubble']`) is clicked — a typed
     * wrapper over the bubbling `aparte-action` DOM event. Switch on `$event.actionId`.
     */
    readonly action = output<AparteActionEventDetail>();
    /** Emitted when messages are updated internally (e.g. by AparteClient) */
    readonly messagesChange = output<AparteMessage[]>();
    /** Emitted when a message is added internally (e.g. by appendMessage) */
    readonly messageAppended = output<AparteMessage>();
    /** The typing/"thinking" indicator toggled (the host flips it off on the first streamed token). */
    readonly typingChange = output<boolean>();
    /** Emitted when the controller lazily creates a conversation on first send. */
    readonly conversationCreated = output<string>();

    // ── View Children ────────────────────────────────────────────────────────
    @ViewChild('viewport') viewportRef?: ElementRef<HTMLElement>;
    @ViewChild('input') inputRef?: ElementRef<HTMLElement>;
    @ViewChildren('bubble') bubbleRefs!: QueryList<ElementRef<HTMLElement>>;

    // ── Private State ────────────────────────────────────────────────────────
    /** Mirror of the host's streaming target id (drives `isStreaming`). */
    private readonly _streamingId = signal<string | null>(null);
    /** Computed: is currently streaming */
    readonly isStreaming = computed(() => this._streamingId() !== null);

    /** rAF id used to coalesce rapid signal updates during streaming */
    private _syncRafId: number | null = null;

    /** The framework-agnostic chat-host orchestrator (created in ngAfterViewInit). */
    private _host?: AparteChatHost;
    private _unbindHost?: () => void;
    /** QueryList.changes subscription — released in ngOnDestroy so SPA route
     *  churn doesn't leak a live subscription per mount. */
    private _bubbleRefsSub?: { unsubscribe(): void };

    ngAfterViewInit(): void {
        const host = this.elementRef.nativeElement as HTMLElement;

        // Ensure a stable id so aparte-composer can reference the host via `target`,
        // letting AparteClient find it without DOM traversal across re-renders.
        if (!host.id) host.id = `aparte-chat-${uuid()}`;
        const composerEl = this.inputRef?.nativeElement;
        if (composerEl) composerEl.setAttribute('target', host.id);

        const binding: AparteChatHostBinding = {
            hostId: host.id,
            host,
            viewport: this.viewportRef?.nativeElement ?? null,
            getMessages: () => this.messages(),
            setMessages: (msgs) => this.messages.set(msgs as AparteMessage[]),
            onMessagesChange: (msgs) => this.messagesChange.emit(msgs as AparteMessage[]),
            onMessageAppended: (msg) => this.messageAppended.emit(msg as AparteMessage),
            onTypingChange: (typing) => { this.isTyping.set(typing); this.typingChange.emit(typing); },
            onStreamingChange: (id) => this._streamingId.set(id),
            // Sibling-info / deferred work runs after Angular has re-rendered.
            afterRender: (cb) => { setTimeout(cb, 0); },
            resetComposer: () => {
                (this.inputRef?.nativeElement as unknown as { reset?: () => void })?.reset?.();
            },
        };

        this._host = new AparteChatHost(binding, {
            layoutTransitionMs: this.layoutTransitionMs,
            conversationId: this._conversationId,
            onConversationCreated: (id) => {
                this._conversationId = id;
                this.conversationCreated.emit(id);
            },
            config: this.config,
        });
        this._unbindHost = this._host.bind();

        // Custom bubble actions bubble to the host as `aparte-action`; surface them as
        // the typed `action` output. (addEventListener, not @HostListener: Angular
        // parses a colon in the event name as a `target:event` global target.)
        host.addEventListener('aparte-action', this._onAction);

        // Re-reconcile bubbles whenever Angular's @for materialises/destroys them.
        this._host.syncBubbles();
        this._bubbleRefsSub = this.bubbleRefs.changes.subscribe(() => this._host?.syncBubbles());
    }

    private readonly _onAction = (event: Event): void => {
        this.action.emit((event as CustomEvent<AparteActionEventDetail>).detail);
    };

    ngOnDestroy(): void {
        if (this._syncRafId !== null) {
            cancelAnimationFrame(this._syncRafId);
            this._syncRafId = null;
        }
        (this.elementRef.nativeElement as HTMLElement).removeEventListener('aparte-action', this._onAction);
        this._bubbleRefsSub?.unsubscribe();
        this._bubbleRefsSub = undefined;
        this._unbindHost?.();
        this._unbindHost = undefined;
        this._host = undefined;
    }

    // ── Public imperative API (delegates to the host) ──────────────────────────

    /** Append a message optimistically — `{ historical: true }` for one restored from your own store. */
    appendMessage(message: AparteMessage, options?: { historical?: boolean }): void {
        this._host?.appendMessage(message, options);
    }
    /** Atomic update for a message. */
    updateMessage(messageId: string, updates: Partial<AparteMessage>): void {
        this._host?.updateMessage(messageId, updates);
    }
    /** Update the last message content (streaming text). */
    updateLastMessage(content: string, options?: { append?: boolean }): void {
        this._host?.updateLastMessage(content, options);
    }
    /** Add a segment to the last message. */
    addSegment(segment: AparteSegment): void { this._host?.addSegment(segment); }
    /** Update a segment in the last message. */
    updateSegment(segmentId: string, updates: Partial<AparteSegment>): void {
        this._host?.updateSegment(segmentId, updates);
    }
    /** Remove a transient segment. */
    removeSegment(segmentId: string): void { this._host?.removeSegment(segmentId); }
    /** Append content to a segment in the last message. */
    appendToSegment(segmentId: string, content: string): void {
        this._host?.appendToSegment(segmentId, content);
    }
    /** Read the current message list. */
    getMessages(): AparteMessage[] { return this._host?.getMessages() ?? this.messages(); }
    /** Clear all messages + reset state. */
    clearMessages(): void { this._host?.clearMessages(); }
    /** Scroll the viewport to the latest message. */
    scrollToBottom(): void {
        (this.viewportRef?.nativeElement as unknown as { scrollToBottom?: () => void })?.scrollToBottom?.();
    }
    /**
     * The `<aparte-chat-viewport>` element — for custom scroll handling, an
     * IntersectionObserver, etc. Same `getViewport()` accessor on all four
     * wrappers.
     */
    getViewport(): HTMLElement | null { return this.viewportRef?.nativeElement ?? null; }
    /** Focus the composer input. */
    focusInput(): void {
        (this.inputRef?.nativeElement as unknown as { focus?: () => void })?.focus?.();
    }
    /** Create a new branch from a message (returns the new sibling index). */
    addBranch(messageId: string): number { return this._host?.addBranch(messageId) ?? 0; }
    /** Add a sibling of an existing message (returns the new id). */
    addSiblingOf(existingId: string, newMessage: AparteMessage): string | null {
        return this._host?.addSiblingOf(existingId, newMessage) ?? null;
    }
    /** Remove a message and all descendants (edit flow). */
    truncateFrom(messageId: string): void { this._host?.truncateFrom(messageId); }
    /** Keep up to and including a user message, drop later responses (retry). */
    truncateResponsesAfter(userMessageId: string): void {
        this._host?.truncateResponsesAfter(userMessageId);
    }

    // ── Token streaming (cross-wrapper contract + Observable adapter) ──────────

    /**
     * Inject a token stream for LLM streaming. Takes the cross-wrapper
     * `AsyncIterable<string>` contract (the exact call that works on
     * React/Vue/Svelte) — or an Angular-idiomatic RxJS `Observable<string>`,
     * adapted into the host's agnostic `streamTokens(AsyncIterable)` so the
     * orphan-stream guard + id tracking stay in one place (the host).
     */
    async injectTokenStream(
        messageId: string,
        stream: Observable<string> | AsyncIterable<string>,
    ): Promise<void> {
        if (!this._host) return;
        const tokens = Symbol.asyncIterator in stream
            ? (stream as AsyncIterable<string>)
            : this._observableToAsyncIterable(stream as Observable<string>);
        await this._host.streamTokens(messageId, tokens);
    }

    /** Stop any active token stream. */
    stopTokenStream(): void { this._host?.stopTokenStream(); }

    /**
     * Set the active conversation id imperatively — parity with the other
     * wrappers' handles (the `conversationId` `@Input` remains the declarative
     * path). Delegates to the host, which loads/persists via the registered
     * `AparteConversationManager`.
     */
    setConversationId(id: string | null): Promise<void> {
        return this._host?.setConversationId(id) ?? Promise.resolve();
    }

    private _observableToAsyncIterable(stream: Observable<string>): AsyncIterable<string> {
        return {
            [Symbol.asyncIterator](): AsyncIterator<string> {
                const buffer: string[] = [];
                let finished = false;
                let failure: unknown = null;
                let pending: {
                    resolve: (r: IteratorResult<string>) => void;
                    reject: (e: unknown) => void;
                } | null = null;
                const settle = () => {
                    if (!pending) return;
                    if (failure !== null) { const p = pending; pending = null; p.reject(failure); return; }
                    if (buffer.length) {
                        const p = pending; pending = null;
                        p.resolve({ value: buffer.shift() as string, done: false });
                        return;
                    }
                    if (finished) {
                        const p = pending; pending = null;
                        p.resolve({ value: undefined as unknown as string, done: true });
                    }
                };
                const sub = stream.subscribe({
                    next: (v) => { buffer.push(v); settle(); },
                    error: (e) => { failure = e; settle(); },
                    complete: () => { finished = true; settle(); },
                });
                return {
                    next(): Promise<IteratorResult<string>> {
                        if (failure !== null) return Promise.reject(failure);
                        if (buffer.length) {
                            return Promise.resolve({ value: buffer.shift() as string, done: false });
                        }
                        if (finished) {
                            return Promise.resolve({ value: undefined as unknown as string, done: true });
                        }
                        return new Promise((resolve, reject) => { pending = { resolve, reject }; });
                    },
                    return(): Promise<IteratorResult<string>> {
                        sub.unsubscribe();
                        // If a consumer is mid-`await next()` on an empty buffer (e.g. the
                        // orphan-stream guard calling `return()` on stop/teardown), settle
                        // that pending promise now with done:true — otherwise it hangs
                        // forever, since unsubscribing means `next` and `complete` will
                        // never fire again to resolve it.
                        if (pending) {
                            const p = pending;
                            pending = null;
                            p.resolve({ value: undefined as unknown as string, done: true });
                        }
                        finished = true;
                        return Promise.resolve({ value: undefined as unknown as string, done: true });
                    },
                };
            },
        };
    }

    /** Handle aparte-send event from the composer Web Component. */
    onAparteSend(event: Event): void {
        const detail = (event as CustomEvent<AparteSendEventDetail>).detail;
        // Smooth-scroll the next auto-scroll (when Angular adds the user bubble).
        (this.viewportRef?.nativeElement as unknown as { requestSmoothScroll?: () => void })
            ?.requestSmoothScroll?.();
        this.messageSent.emit(detail);
    }
}

// packages/wrappers/svelte/src/lib/AparteChat.svelte
<script lang="ts">
  import { onMount, onDestroy, tick, createEventDispatcher } from 'svelte';
  import { AparteChatHost, isAwaitingReply, type AparteChatHostBinding, type AparteConfig, type AparteChatImperativeApi, uuid } from '@aparte/core';
  import type { AparteMessage, AparteSegment, AparteSendEventDetail, AparteActionEventDetail } from './types';

  /**
   * The host element's `id`, and therefore the `targetId` every event this chat
   * dispatches carries. Generated when omitted — but it used to be generated and
   * neither accepted nor exposed, which made `scopeToTargetId` unreachable from
   * this component.
   */
  export let id: string | undefined = undefined;
  export let messages: AparteMessage[] = [];
  export let placeholder = 'Type a message...';
  export let disabled = false;
  export let isTyping = false;
  export let typingText = 'Assistant is thinking...';
  /** When false, Shift+Enter submits and a bare Enter inserts a newline. */
  export let submitOnEnter = true;
  /** Freeze viewport spacer recalculation for this many ms after a conv swap. */
  export let layoutTransitionMs = 0;
  /**
   * Opt in to the "centered composer when empty" layout: the composer sits
   * vertically centered with the `empty-state` slot above it while the list is
   * empty, then slides to the bottom on the first message (~0.3s). Off by
   * default — additive.
   */
  export let centerWhenEmpty = false;
  /** Overlay the composer on the transcript: full-column scroll surface, edge-to-edge scrollbar, floating composer. Read when the viewport mounts. */
  export let overlayComposer = false;
  /**
   * Add the file picker + chips strip to the default composer shell. **Off by
   * default**, because the capability needs a host that consumes the files: an
   * `AparteClient` inlines them per its `rawFileInject` option, but if you drive
   * your own loop you must read `event.files` on `messageSent` — otherwise the file
   * the user deliberately attached is dropped in silence. No effect when you fill
   * the `composer` slot (drop `<aparte-composer-add-attachment>` and
   * `<aparte-composer-attachments>` in it yourself).
   */
  export let attachments = false;
  /**
   * Render the `<aparte-elicitation>` presenter inside the host — on by default, as it
   * is in `<aparte-chat>`: the built-in approval gate and `requestUserInput()` ask
   * through it, and it renders nothing until something asks. Pass `false` when you
   * mount a presenter of your own (`setElicitationPresenter`) or place the element
   * yourself.
   */
  export let elicitation = true;
  /** Extra class names for the root element (`[data-aparte-chat]`), merged after core's own. */
  let className = '';
  export { className as class };
  /** Inline style for the root element (`[data-aparte-chat]`). */
  export let style: string | undefined = undefined;
  /** Active conversation id (loads/persists via the registered AparteConversationManager). */
  export let conversationId: string | null = null;
  /**
   * Instance {@link AparteConfig} for this chat. When set, aparté components
   * inside resolve THIS config instead of `aparteGlobalConfig`, so
   * several independently-configured chats can coexist on one page. Omit for the
   * global config. Read once when the host mounts.
   */
  export let config: AparteConfig | undefined = undefined;

  /*
   * Callback props, called with the payload itself, alongside the events below (#47).
   * Svelte 5 documents `createEventDispatcher` as deprecated and recommends callback
   * props; a Svelte 4 consumer keeps `on:` and sees nothing change, a Svelte 5 one
   * never writes `on:` on a component. Both routes fire for the same occurrence, in
   * this order: the callback, then the event.
   */
  /** User submitted a message from the composer — see `messageSent` below for the append rule. */
  export let onmessageSent: ((detail: AparteSendEventDetail) => void) | undefined = undefined;
  /** A custom bubble action (registerBubbleAction) was clicked. */
  export let onaction: ((detail: AparteActionEventDetail) => void) | undefined = undefined;
  /** Active path changed — the list to bind back to `messages`. */
  export let onmessagesChange: ((messages: AparteMessage[]) => void) | undefined = undefined;
  /** One message was appended. */
  export let onmessageAppended: ((message: AparteMessage) => void) | undefined = undefined;
  /** The typing/"thinking" indicator toggled. */
  export let ontypingChange: ((typing: boolean) => void) | undefined = undefined;
  /** The host created a conversation id (persistence). */
  export let onconversationCreated: ((id: string) => void) | undefined = undefined;

  const dispatch = createEventDispatcher<{
    /**
     * User submitted a message from the composer. It is **appended to the
     * thread automatically** (optimistic UI) before this fires — do NOT add it
     * again (uncontrolled → duplicates; controlled → mirror into your own
     * `messages`). For side-effects: scroll, analytics, send.
     */
    messageSent: AparteSendEventDetail;
    /** A custom bubble action (registerBubbleAction) was clicked — typed aparte-action. */
    action: AparteActionEventDetail;
    /** Active path changed (branch nav/edit/retry/streaming) — bind back to `messages`. */
    messagesChange: AparteMessage[];
    messageAppended: AparteMessage;
    /** The typing/"thinking" indicator toggled (the host flips it off on the first streamed token). */
    typingChange: boolean;
    conversationCreated: string;
  }>();

  // Generated client-side in onMount (below): during SSR this stays empty so the
  // server and first client render agree on the id — no hydration mismatch.
  let hostId = '';

  let rootRef: HTMLElement;
  let viewportRef: HTMLElement;
  let composerRef: HTMLElement;
  let internalMessages: AparteMessage[] = [...messages];
  let typingActive = isTyping;
  let host: AparteChatHost | null = null;
  let teardown: (() => void) | null = null;

  // Parent push → internal list (guarded against the host's own emit round-trip).
  let lastProp = messages;
  $: if (messages !== lastProp) {
    lastProp = messages;
    internalMessages = [...messages];
    if (messages.length === 0) host?.clearRenderCache();
  }

  // Controlled typing indicator (host may flip it off on the first token).
  let lastTyping = isTyping;
  $: if (isTyping !== lastTyping) { lastTyping = isTyping; typingActive = isTyping; }

  // Conversation id changes (initial value loaded by the host on bind).
  let lastConv = conversationId;
  $: if (conversationId !== lastConv) {
    lastConv = conversationId;
    void host?.setConversationId(conversationId ?? null);
  }

  // Reconcile bubbles after the rendered list changes (host queries the DOM).
  $: if (host && internalMessages) { void tick().then(() => host?.syncBubbles()); }

  // Composer attributes set imperatively (like Angular's `[attr.x]`): Svelte's
  // custom-element binding assigns to *properties*, but aparte-composer exposes
  // some of these (e.g. `placeholder`) as getter-only — assigning throws.
  function toggleAttr(el: HTMLElement, name: string, on: boolean, value: string) {
    if (on) el.setAttribute(name, value); else el.removeAttribute(name);
  }
  $: if (composerRef) {
    composerRef.setAttribute('target', hostId);
    composerRef.setAttribute('placeholder', placeholder);
    toggleAttr(composerRef, 'disabled', disabled, '');
    toggleAttr(composerRef, 'submit-on-enter', !submitOnEnter, 'false');
  }

  function handleSend(event: Event) {
    (viewportRef as unknown as { requestSmoothScroll?: () => void })?.requestSmoothScroll?.();
    const detail = (event as CustomEvent<AparteSendEventDetail>).detail;
    onmessageSent?.(detail);
    dispatch('messageSent', detail);
  }

  // Custom bubble actions bubble to the root as `aparte-action` — dispatch typed.
  function handleAction(event: Event) {
    const detail = (event as CustomEvent<AparteActionEventDetail>).detail;
    onaction?.(detail);
    dispatch('action', detail);
  }

  onMount(() => {
    // A caller-supplied `id` wins, so `scopeToTargetId` has something to match.
    hostId = id ?? `aparte-chat-${uuid()}`;
    // Set the id imperatively (deterministic, like Angular's ngAfterViewInit) rather
    // than waiting on a reactive re-render of `id={hostId}`; the composer target
    // reactive block below picks up the same hostId.
    if (rootRef) rootRef.id = hostId;
    const binding: AparteChatHostBinding = {
      hostId,
      host: rootRef,
      viewport: viewportRef,
      getMessages: () => internalMessages,
      setMessages: (m) => { internalMessages = m as AparteMessage[]; },
      onMessagesChange: (m) => { onmessagesChange?.(m as AparteMessage[]); dispatch('messagesChange', m as AparteMessage[]); },
      onMessageAppended: (m) => { onmessageAppended?.(m as AparteMessage); dispatch('messageAppended', m as AparteMessage); },
      onTypingChange: (t) => { typingActive = t; ontypingChange?.(t); dispatch('typingChange', t); },
      onStreamingChange: () => { /* exposed via isStreaming() */ },
      afterRender: (cb) => { void tick().then(cb); },
      resetComposer: () => (composerRef as unknown as { reset?: () => void })?.reset?.(),
    };
    host = new AparteChatHost(binding, {
      layoutTransitionMs,
      conversationId: conversationId ?? null,
      onConversationCreated: (id) => { onconversationCreated?.(id); dispatch('conversationCreated', id); },
      config,
    });
    teardown = host.bind();
    host.syncBubbles();
    rootRef?.addEventListener('aparte-action', handleAction);
  });

  onDestroy(() => {
    rootRef?.removeEventListener('aparte-action', handleAction);
    teardown?.();
    teardown = null;
    host = null;
  });

  // ── Imperative API (bind:this on the component) ──
  export function appendMessage(m: AparteMessage, options?: { historical?: boolean }) { host?.appendMessage(m, options); }
  export function updateMessage(id: string, u: Partial<AparteMessage>) { host?.updateMessage(id, u); }
  export function updateLastMessage(content: string, options?: { append?: boolean }) {
    host?.updateLastMessage(content, options);
  }
  export function addSegment(segment: AparteSegment) { host?.addSegment(segment); }
  export function updateSegment(segmentId: string, updates: Partial<AparteSegment>) {
    host?.updateSegment(segmentId, updates);
  }
  export function removeSegment(segmentId: string) { host?.removeSegment(segmentId); }
  export function appendToSegment(segmentId: string, content: string) {
    host?.appendToSegment(segmentId, content);
  }
  export function getMessages(): AparteMessage[] { return host?.getMessages() ?? internalMessages; }
  export function clearMessages() { host?.clearMessages(); }
  export function addBranch(messageId: string): number { return host?.addBranch(messageId) ?? 0; }
  export function addSiblingOf(existingId: string, message: AparteMessage): string | null {
    return host?.addSiblingOf(existingId, message) ?? null;
  }
  export function truncateFrom(messageId: string) { host?.truncateFrom(messageId); }
  export function truncateResponsesAfter(userMessageId: string) {
    host?.truncateResponsesAfter(userMessageId);
  }
  export function injectTokenStream(messageId: string, tokens: AsyncIterable<string>): Promise<void> {
    return host?.streamTokens(messageId, tokens) ?? Promise.resolve();
  }
  export function stopTokenStream() { host?.stopTokenStream(); }
  export function setConversationId(id: string | null): Promise<void> {
    return host?.setConversationId(id) ?? Promise.resolve();
  }
  export function scrollToBottom() {
    (viewportRef as unknown as { scrollToBottom?: () => void })?.scrollToBottom?.();
  }
  /**
   * The `<aparte-chat-viewport>` element — for custom scroll handling, an
   * IntersectionObserver, etc. Same `getViewport()` accessor on all four
   * wrappers.
   */
  export function getViewport(): HTMLElement | null { return viewportRef ?? null; }
  export function focusInput() {
    (composerRef as unknown as { focus?: () => void })?.focus?.();
  }
  export function isStreaming(): boolean { return host?.isStreaming ?? false; }

  // Compile-time parity check: Svelte 4 can't generic-annotate `export function`s,
  // so this never-called factory type-checks that the exported surface matches the
  // canonical AparteChatImperativeApi. A dropped/mistyped method is a build error.
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  function _assertImperativeParity(): AparteChatImperativeApi {
    return {
      appendMessage, updateMessage, updateLastMessage, addSegment, updateSegment, removeSegment,
      appendToSegment, getMessages, clearMessages, addBranch, addSiblingOf, truncateFrom,
      truncateResponsesAfter, injectTokenStream, stopTokenStream, setConversationId,
      scrollToBottom, focusInput, isStreaming, getViewport,
    };
  }
</script>

<div
  class="aparte-chat-container {className}"
  class:aparte-chat-container--auto-center={centerWhenEmpty}
  {style}
  data-aparte-chat
  {...(overlayComposer ? { 'overlay-composer': '' } : {})}
  data-aparte-empty={centerWhenEmpty && internalMessages.length === 0 ? '' : null}
  id={hostId}
  bind:this={rootRef}
>
  <aparte-chat-viewport bind:this={viewportRef} framework-managed="">
    <!-- Welcome / placeholder shown inside the viewport while empty. -->
    {#if internalMessages.length === 0}
      <slot name="empty-state" />
    {/if}
    <!-- `bubble` slot renders your OWN element per message in place of
         <aparte-chat-bubble>; driven by the reactive list so it streams live. -->
    {#each internalMessages as m (m.id)}
      <slot name="bubble" message={m}>
        <aparte-chat-bubble
          message-id={m.id}
          data-role={m.role}
          data-kind={m.compaction ? 'compaction' : undefined}
          timestamp={m.timestamp}
          content={m.content}
          streaming={isAwaitingReply(m) ? '' : null}></aparte-chat-bubble>
      </slot>
    {/each}
    <aparte-chat-status visible={typingActive ? '' : null} text={typingText}></aparte-chat-status>
  </aparte-chat-viewport>

  <!-- The presenter for a request to the human (approval gate, ask_user…). Renders
       nothing until something asks; on by default as in <aparte-chat>. -->
  {#if elicitation}<aparte-elicitation></aparte-elicitation>{/if}

  <!-- Content above the composer (banner, disclaimer, context chip). -->
  <slot name="above-composer" />

  <aparte-composer
    bind:this={composerRef}
    on:aparte-send={handleSend}
  >
    <!-- Custom composer via the `composer` slot; falls back to the default
         shell (input · send, plus the attachment primitives when `attachments` is
         set). Compose the headless aparte-composer-* primitives freely for a
         skin-specific layout. -->
    <slot name="composer">
      <div class="aparte-composer-shell">
        {#if attachments}<aparte-composer-attachments></aparte-composer-attachments>{/if}
        <div class="aparte-composer-row">
          {#if attachments}<aparte-composer-add-attachment></aparte-composer-add-attachment>{/if}
          <aparte-composer-input></aparte-composer-input>
          <aparte-composer-send></aparte-composer-send>
        </div>
        <!-- The composer's bottom row. ONE slot: placement is the DOM order, and
             `margin-inline-start: auto` pushes a control to the end (a logical
             property, so it reads correctly in RTL). Nothing is rendered at all when
             the slot is unused. -->
        {#if $$slots.toolbar}
          <aparte-composer-toolbar>
            <slot name="toolbar" />
          </aparte-composer-toolbar>
        {/if}
      </div>
    </slot>
  </aparte-composer>
</div>
